namespace M2Server
{
  partial class TfrmActionSpeed
    {
        private System.Windows.Forms.Label Label5;
        private System.Windows.Forms.GroupBox GroupBox1;
        private System.Windows.Forms.GroupBox GroupBox3;
        private System.Windows.Forms.Label Label15;
        private System.Windows.Forms.NumericUpDown EditRunLongHitIntervalTime;
        private System.Windows.Forms.CheckBox CheckBoxControlRunLongHit;
        private System.Windows.Forms.GroupBox GroupBox2;
        private System.Windows.Forms.Label Label2;
        private System.Windows.Forms.NumericUpDown EditActionIntervalTime;
        private System.Windows.Forms.CheckBox CheckBoxControlActionInterval;
        private System.Windows.Forms.GroupBox GroupBox4;
        private System.Windows.Forms.Label Label1;
        private System.Windows.Forms.NumericUpDown EditRunHitIntervalTime;
        private System.Windows.Forms.CheckBox CheckBoxControlRunHit;
        private System.Windows.Forms.GroupBox GroupBox5;
        private System.Windows.Forms.Label Label3;
        private System.Windows.Forms.NumericUpDown EditWalkHitIntervalTime;
        private System.Windows.Forms.CheckBox CheckBoxControlWalkHit;
        private System.Windows.Forms.GroupBox GroupBox6;
        private System.Windows.Forms.Label Label4;
        private System.Windows.Forms.NumericUpDown EditRunMagicIntervalTime;
        private System.Windows.Forms.CheckBox CheckBoxControlRunMagic;
        private System.Windows.Forms.Button ButtonSave;
        private System.Windows.Forms.Button ButtonDefault;
        private System.Windows.Forms.Button ButtonClose;
        private System.Windows.Forms.CheckBox CheckBoxIncremeng;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.Label5 = new System.Windows.Forms.Label();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.Label15 = new System.Windows.Forms.Label();
            this.EditRunLongHitIntervalTime = new System.Windows.Forms.NumericUpDown();
            this.CheckBoxControlRunLongHit = new System.Windows.Forms.CheckBox();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.EditActionIntervalTime = new System.Windows.Forms.NumericUpDown();
            this.CheckBoxControlActionInterval = new System.Windows.Forms.CheckBox();
            this.GroupBox4 = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.EditRunHitIntervalTime = new System.Windows.Forms.NumericUpDown();
            this.CheckBoxControlRunHit = new System.Windows.Forms.CheckBox();
            this.GroupBox5 = new System.Windows.Forms.GroupBox();
            this.Label3 = new System.Windows.Forms.Label();
            this.EditWalkHitIntervalTime = new System.Windows.Forms.NumericUpDown();
            this.CheckBoxControlWalkHit = new System.Windows.Forms.CheckBox();
            this.GroupBox6 = new System.Windows.Forms.GroupBox();
            this.Label4 = new System.Windows.Forms.Label();
            this.EditRunMagicIntervalTime = new System.Windows.Forms.NumericUpDown();
            this.CheckBoxControlRunMagic = new System.Windows.Forms.CheckBox();
            this.ButtonSave = new System.Windows.Forms.Button();
            this.ButtonDefault = new System.Windows.Forms.Button();
            this.ButtonClose = new System.Windows.Forms.Button();
            this.CheckBoxIncremeng = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(515, 413);
            this.ClientSize  = new System.Drawing.Size(318, 257);
            this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(134)));
            this.AutoScroll = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.ActiveControl = ButtonClose;
            this.Name = "frmActionSpeed";
            this.Text = "组合操作速度设置";
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.Label5.Size  = new System.Drawing.Size(288, 12);
            this.Label5.Location  = new System.Drawing.Point(8, 240);
            this.Label5.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.Label5.Text = "参数调整后，在游戏中人物小退后生效，非立即生效。";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.GroupBox1.Size  = new System.Drawing.Size(297, 193);
            this.GroupBox1.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.TabIndex = 0;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.GroupBox3.Size  = new System.Drawing.Size(137, 49);
            this.GroupBox3.Location  = new System.Drawing.Point(152, 16);
            this.GroupBox3.SuspendLayout();
            this.GroupBox3.TabIndex = 0;
            this.GroupBox3.Enabled = true;
            this.GroupBox3.Name = "GroupBox3";
            this.Label15.Size  = new System.Drawing.Size(54, 12);
            this.Label15.Location  = new System.Drawing.Point(11, 24);
            this.Label15.Text = "跑位间隔:";
            this.Label15.Enabled = true;
            this.Label15.Name = "Label15";
            ((System.ComponentModel.ISupportInitialize)(this.EditRunLongHitIntervalTime)).BeginInit();
            this.EditRunLongHitIntervalTime.Size  = new System.Drawing.Size(53, 21);
            this.EditRunLongHitIntervalTime.Location  = new System.Drawing.Point(68, 20);
            this.EditRunLongHitIntervalTime.Value = 350;
            this.EditRunLongHitIntervalTime.TabIndex = 0;
            this.EditRunLongHitIntervalTime.Increment = 10;
            this.EditRunLongHitIntervalTime.Name = "EditRunLongHitIntervalTime";
            this.EditRunLongHitIntervalTime.Enabled = true;
            this.toolTip1.SetToolTip(this.EditRunLongHitIntervalTime, "控制跑位刺杀攻击间隔时间，单位为(毫秒)。");
            this.CheckBoxControlRunLongHit.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxControlRunLongHit.Location  = new System.Drawing.Point(8, -1);
            this.CheckBoxControlRunLongHit.Text = "启用跑位刺杀控制";
            this.CheckBoxControlRunLongHit.TabIndex = 1;
            this.CheckBoxControlRunLongHit.Enabled = true;
            //this.CheckBoxControlRunLongHit.Click += new System.EventHandler(this.CheckBoxControlRunLongHitClick);
            this.CheckBoxControlRunLongHit.Name = "CheckBoxControlRunLongHit";
            this.toolTip1.SetToolTip(this.CheckBoxControlRunLongHit, "是否对跑位刺杀进行控制。");
            this.GroupBox2.Size  = new System.Drawing.Size(137, 49);
            this.GroupBox2.Location  = new System.Drawing.Point(8, 16);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.Text = "组合操作间隔";
            this.GroupBox2.TabIndex = 1;
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label2.Size  = new System.Drawing.Size(54, 12);
            this.Label2.Location  = new System.Drawing.Point(11, 24);
            this.Label2.Text = "间隔时间:";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            ((System.ComponentModel.ISupportInitialize)(this.EditActionIntervalTime)).BeginInit();
            this.EditActionIntervalTime.Size  = new System.Drawing.Size(53, 21);
            this.EditActionIntervalTime.Location  = new System.Drawing.Point(68, 20);
            this.EditActionIntervalTime.Value = 350;
            this.EditActionIntervalTime.TabIndex = 0;
            this.EditActionIntervalTime.Increment = 10;
            this.EditActionIntervalTime.Name = "EditActionIntervalTime";
            this.EditActionIntervalTime.Enabled = true;
            this.toolTip1.SetToolTip(this.EditActionIntervalTime, "控制组合普通操作间隔时间，单位为(毫秒)。");
            this.CheckBoxControlActionInterval.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxControlActionInterval.Location  = new System.Drawing.Point(8, -1);
            this.CheckBoxControlActionInterval.Text = "启用组合操作控制";
            this.CheckBoxControlActionInterval.TabIndex = 2;
            this.CheckBoxControlActionInterval.Enabled = true;
            //this.CheckBoxControlActionInterval.Click += new System.EventHandler(this.CheckBoxControlActionIntervalClick);
            this.CheckBoxControlActionInterval.Name = "CheckBoxControlActionInterval";
            this.toolTip1.SetToolTip(this.CheckBoxControlActionInterval, "是否对组合操作进行控制。");
            this.GroupBox4.Size  = new System.Drawing.Size(137, 49);
            this.GroupBox4.Location  = new System.Drawing.Point(8, 72);
            this.GroupBox4.SuspendLayout();
            this.GroupBox4.TabIndex = 3;
            this.GroupBox4.Enabled = true;
            this.GroupBox4.Name = "GroupBox4";
            this.Label1.Size  = new System.Drawing.Size(54, 12);
            this.Label1.Location  = new System.Drawing.Point(11, 24);
            this.Label1.Text = "跑位间隔:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            ((System.ComponentModel.ISupportInitialize)(this.EditRunHitIntervalTime)).BeginInit();
            this.EditRunHitIntervalTime.Size  = new System.Drawing.Size(53, 21);
            this.EditRunHitIntervalTime.Location  = new System.Drawing.Point(68, 20);
            this.EditRunHitIntervalTime.Value = 350;
            this.EditRunHitIntervalTime.TabIndex = 0;
            this.EditRunHitIntervalTime.Increment = 10;
            this.EditRunHitIntervalTime.Name = "EditRunHitIntervalTime";
            this.EditRunHitIntervalTime.Enabled = true;
            this.toolTip1.SetToolTip(this.EditRunHitIntervalTime, "控制跑位攻击间隔时间，单位为(毫秒)。");
            this.CheckBoxControlRunHit.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxControlRunHit.Location  = new System.Drawing.Point(8, -1);
            this.CheckBoxControlRunHit.Text = "启用跑位攻击控制";
            this.CheckBoxControlRunHit.TabIndex = 1;
            this.CheckBoxControlRunHit.Enabled = true;
            //this.CheckBoxControlRunHit.Click += new System.EventHandler(this.CheckBoxControlRunHitClick);
            this.CheckBoxControlRunHit.Name = "CheckBoxControlRunHit";
            this.toolTip1.SetToolTip(this.CheckBoxControlRunHit, "是否对跑位攻击进行控制。");
            this.GroupBox5.Size  = new System.Drawing.Size(137, 49);
            this.GroupBox5.Location  = new System.Drawing.Point(152, 72);
            this.GroupBox5.SuspendLayout();
            this.GroupBox5.TabIndex = 4;
            this.GroupBox5.Enabled = true;
            this.GroupBox5.Name = "GroupBox5";
            this.Label3.Size  = new System.Drawing.Size(54, 12);
            this.Label3.Location  = new System.Drawing.Point(11, 24);
            this.Label3.Text = "走位间隔:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            ((System.ComponentModel.ISupportInitialize)(this.EditWalkHitIntervalTime)).BeginInit();
            this.EditWalkHitIntervalTime.Size  = new System.Drawing.Size(53, 21);
            this.EditWalkHitIntervalTime.Location  = new System.Drawing.Point(68, 20);
            this.EditWalkHitIntervalTime.Value = 350;
            this.EditWalkHitIntervalTime.TabIndex = 0;
            this.EditWalkHitIntervalTime.Increment = 10;
            this.EditWalkHitIntervalTime.Name = "EditWalkHitIntervalTime";
            this.EditWalkHitIntervalTime.Enabled = true;
            this.toolTip1.SetToolTip(this.EditWalkHitIntervalTime, "控制走位攻击间隔时间，单位为(毫秒)。");
            this.CheckBoxControlWalkHit.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxControlWalkHit.Location  = new System.Drawing.Point(8, -1);
            this.CheckBoxControlWalkHit.Text = "启用走位攻击控制";
            this.CheckBoxControlWalkHit.TabIndex = 1;
            this.CheckBoxControlWalkHit.Enabled = true;
            //this.CheckBoxControlWalkHit.Click += new System.EventHandler(this.CheckBoxControlWalkHitClick);
            this.CheckBoxControlWalkHit.Name = "CheckBoxControlWalkHit";
            this.toolTip1.SetToolTip(this.CheckBoxControlWalkHit, "是否对跑位攻击进行控制。");
            this.GroupBox6.Size  = new System.Drawing.Size(137, 49);
            this.GroupBox6.Location  = new System.Drawing.Point(8, 128);
            this.GroupBox6.SuspendLayout();
            this.GroupBox6.TabIndex = 5;
            this.GroupBox6.Enabled = true;
            this.GroupBox6.Name = "GroupBox6";
            this.Label4.Size  = new System.Drawing.Size(54, 12);
            this.Label4.Location  = new System.Drawing.Point(11, 24);
            this.Label4.Text = "跑位间隔:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            ((System.ComponentModel.ISupportInitialize)(this.EditRunMagicIntervalTime)).BeginInit();
            this.EditRunMagicIntervalTime.Size  = new System.Drawing.Size(53, 21);
            this.EditRunMagicIntervalTime.Location  = new System.Drawing.Point(68, 20);
            this.EditRunMagicIntervalTime.Value = 350;
            this.EditRunMagicIntervalTime.TabIndex = 0;
            this.EditRunMagicIntervalTime.Increment = 10;
            this.EditRunMagicIntervalTime.Name = "EditRunMagicIntervalTime";
            this.EditRunMagicIntervalTime.Enabled = true;
            this.toolTip1.SetToolTip(this.EditRunMagicIntervalTime, "控制跑位魔法间隔时间，单位为(毫秒)。");
            this.CheckBoxControlRunMagic.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxControlRunMagic.Location  = new System.Drawing.Point(8, -1);
            this.CheckBoxControlRunMagic.Text = "启用跑位魔法控制";
            this.CheckBoxControlRunMagic.TabIndex = 1;
            this.CheckBoxControlRunMagic.Enabled = true;
            //this.CheckBoxControlRunMagic.Click += new System.EventHandler(this.CheckBoxControlRunMagicClick);
            this.CheckBoxControlRunMagic.Name = "CheckBoxControlRunMagic";
            this.toolTip1.SetToolTip(this.CheckBoxControlRunMagic, "是否对跑位攻击进行控制。");
            this.ButtonSave.Size  = new System.Drawing.Size(65, 25);
            this.ButtonSave.Location  = new System.Drawing.Point(80, 205);
            //this.ButtonSave.Click += new System.EventHandler(this.ButtonSaveClick);
            this.ButtonSave.TabIndex = 1;
            this.ButtonSave.Name = "ButtonSave";
            this.ButtonSave.Enabled = true;
            this.ButtonSave.Text = "保存(&S)";
            this.ButtonSave.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ButtonDefault.Size  = new System.Drawing.Size(65, 25);
            this.ButtonDefault.Location  = new System.Drawing.Point(8, 205);
            //this.ButtonDefault.Click += new System.EventHandler(this.ButtonDefaultClick);
            this.ButtonDefault.TabIndex = 2;
            this.ButtonDefault.Name = "ButtonDefault";
            this.ButtonDefault.Enabled = true;
            this.ButtonDefault.Text = "默认(&D)";
            this.ButtonDefault.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ButtonClose.Size  = new System.Drawing.Size(65, 25);
            this.ButtonClose.Location  = new System.Drawing.Point(240, 204);
            //this.ButtonClose.Click += new System.EventHandler(this.ButtonCloseClick);
            this.ButtonClose.TabIndex = 3;
            this.ButtonClose.Name = "ButtonClose";
            this.ButtonClose.Enabled = true;
            this.ButtonClose.Text = "关闭(&C)";
            this.ButtonClose.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.CheckBoxIncremeng.Size  = new System.Drawing.Size(73, 17);
            this.CheckBoxIncremeng.Location  = new System.Drawing.Point(160, 208);
            this.CheckBoxIncremeng.Text = "微调参数";
            this.CheckBoxIncremeng.TabIndex = 4;
            this.CheckBoxIncremeng.Enabled = true;
            //this.CheckBoxIncremeng.Click += new System.EventHandler(this.CheckBoxIncremengClick);
            this.CheckBoxIncremeng.Name = "CheckBoxIncremeng";
            this.GroupBox3.Controls.Add(Label15);
            this.GroupBox3.Controls.Add(EditRunLongHitIntervalTime);
            this.GroupBox3.Controls.Add(CheckBoxControlRunLongHit);
            ((System.ComponentModel.ISupportInitialize)(this.EditRunLongHitIntervalTime)).EndInit();
            this.GroupBox3.ResumeLayout(false);
            this.GroupBox2.Controls.Add(Label2);
            this.GroupBox2.Controls.Add(EditActionIntervalTime);
            ((System.ComponentModel.ISupportInitialize)(this.EditActionIntervalTime)).EndInit();
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox4.Controls.Add(Label1);
            this.GroupBox4.Controls.Add(EditRunHitIntervalTime);
            this.GroupBox4.Controls.Add(CheckBoxControlRunHit);
            ((System.ComponentModel.ISupportInitialize)(this.EditRunHitIntervalTime)).EndInit();
            this.GroupBox4.ResumeLayout(false);
            this.GroupBox5.Controls.Add(Label3);
            this.GroupBox5.Controls.Add(EditWalkHitIntervalTime);
            this.GroupBox5.Controls.Add(CheckBoxControlWalkHit);
            ((System.ComponentModel.ISupportInitialize)(this.EditWalkHitIntervalTime)).EndInit();
            this.GroupBox5.ResumeLayout(false);
            this.GroupBox6.Controls.Add(Label4);
            this.GroupBox6.Controls.Add(EditRunMagicIntervalTime);
            this.GroupBox6.Controls.Add(CheckBoxControlRunMagic);
            ((System.ComponentModel.ISupportInitialize)(this.EditRunMagicIntervalTime)).EndInit();
            this.GroupBox6.ResumeLayout(false);
            this.GroupBox1.Controls.Add(GroupBox3);
            this.GroupBox1.Controls.Add(GroupBox2);
            this.GroupBox1.Controls.Add(CheckBoxControlActionInterval);
            this.GroupBox1.Controls.Add(GroupBox4);
            this.GroupBox1.Controls.Add(GroupBox5);
            this.GroupBox1.Controls.Add(GroupBox6);
            this.GroupBox1.ResumeLayout(false);
            this.Controls.Add(Label5);
            this.Controls.Add(GroupBox1);
            this.Controls.Add(ButtonSave);
            this.Controls.Add(ButtonDefault);
            this.Controls.Add(ButtonClose);
            this.Controls.Add(CheckBoxIncremeng);
            this.ResumeLayout(false);
        }
#endregion

    }
}
