namespace M2Server
{
  partial class TfrmGameCmd
    {
        private System.Windows.Forms.TabControl PageControl;
        private System.Windows.Forms.TabPage TabSheet1;
        private System.Windows.Forms.DataGrid StringGridGameCmd;
        private System.Windows.Forms.GroupBox GroupBox1;
        private System.Windows.Forms.Label Label1;
        private System.Windows.Forms.Label Label6;
        private System.Windows.Forms.Label LabelUserCmdFunc;
        private System.Windows.Forms.Label LabelUserCmdParam;
        private System.Windows.Forms.Label Label2;
        private System.Windows.Forms.Label Label3;
        private System.Windows.Forms.TextBox EditUserCmdName;
        private System.Windows.Forms.NumericUpDown EditUserCmdPerMission;
        private System.Windows.Forms.Button EditUserCmdOK;
        private System.Windows.Forms.Button EditUserCmdSave;
        private System.Windows.Forms.TabPage TabSheet2;
        private System.Windows.Forms.DataGrid StringGridGameMasterCmd;
        private System.Windows.Forms.GroupBox GroupBox2;
        private System.Windows.Forms.Label Label4;
        private System.Windows.Forms.Label Label5;
        private System.Windows.Forms.Label LabelGameMasterCmdFunc;
        private System.Windows.Forms.Label LabelGameMasterCmdParam;
        private System.Windows.Forms.Label Label7;
        private System.Windows.Forms.Label Label8;
        private System.Windows.Forms.TextBox EditGameMasterCmdName;
        private System.Windows.Forms.NumericUpDown EditGameMasterCmdPerMission;
        private System.Windows.Forms.Button EditGameMasterCmdOK;
        private System.Windows.Forms.Button EditGameMasterCmdSave;
        private System.Windows.Forms.TabPage TabSheet3;
        private System.Windows.Forms.DataGrid StringGridGameDebugCmd;
        private System.Windows.Forms.GroupBox GroupBox3;
        private System.Windows.Forms.Label Label9;
        private System.Windows.Forms.Label Label10;
        private System.Windows.Forms.Label LabelGameDebugCmdFunc;
        private System.Windows.Forms.Label LabelGameDebugCmdParam;
        private System.Windows.Forms.Label Label11;
        private System.Windows.Forms.Label Label12;
        private System.Windows.Forms.TextBox EditGameDebugCmdName;
        private System.Windows.Forms.NumericUpDown EditGameDebugCmdPerMission;
        private System.Windows.Forms.Button EditGameDebugCmdOK;
        private System.Windows.Forms.Button EditGameDebugCmdSave;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        //Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.PageControl = new System.Windows.Forms.TabControl();
            this.TabSheet1 = new System.Windows.Forms.TabPage();
            this.StringGridGameCmd = new System.Windows.Forms.DataGrid();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.LabelUserCmdFunc = new System.Windows.Forms.Label();
            this.LabelUserCmdParam = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.EditUserCmdName = new System.Windows.Forms.TextBox();
            this.EditUserCmdPerMission = new System.Windows.Forms.NumericUpDown();
            this.EditUserCmdOK = new System.Windows.Forms.Button();
            this.EditUserCmdSave = new System.Windows.Forms.Button();
            this.TabSheet2 = new System.Windows.Forms.TabPage();
            this.StringGridGameMasterCmd = new System.Windows.Forms.DataGrid();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.LabelGameMasterCmdFunc = new System.Windows.Forms.Label();
            this.LabelGameMasterCmdParam = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.EditGameMasterCmdName = new System.Windows.Forms.TextBox();
            this.EditGameMasterCmdPerMission = new System.Windows.Forms.NumericUpDown();
            this.EditGameMasterCmdOK = new System.Windows.Forms.Button();
            this.EditGameMasterCmdSave = new System.Windows.Forms.Button();
            this.TabSheet3 = new System.Windows.Forms.TabPage();
            this.StringGridGameDebugCmd = new System.Windows.Forms.DataGrid();
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.LabelGameDebugCmdFunc = new System.Windows.Forms.Label();
            this.LabelGameDebugCmdParam = new System.Windows.Forms.Label();
            this.Label11 = new System.Windows.Forms.Label();
            this.Label12 = new System.Windows.Forms.Label();
            this.EditGameDebugCmdName = new System.Windows.Forms.TextBox();
            this.EditGameDebugCmdPerMission = new System.Windows.Forms.NumericUpDown();
            this.EditGameDebugCmdOK = new System.Windows.Forms.Button();
            this.EditGameDebugCmdSave = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(343, 294);
            this.ClientSize  = new System.Drawing.Size(673, 417);
            this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(134)));
           // this.Closed += new System.EventHandler(this.FormClose);
            this.Name = "frmGameCmd";
            this.Text = "游戏命令设置";
            //this.Load += new System.EventHandler(this.FormCreate);
            this.AutoScroll = true;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.PageControl.Size  = new System.Drawing.Size(657, 401);
            this.PageControl.Location  = new System.Drawing.Point(8, 8);
            this.PageControl.SuspendLayout();
            this.PageControl.SelectedTab = TabSheet1;
            this.PageControl.HotTrack = true;
            this.PageControl.TabIndex = 0;
            this.PageControl.Enabled = true;
            this.PageControl.Name = "PageControl";
            this.TabSheet1.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet1.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet1.SuspendLayout();
            this.TabSheet1.Text = "普通命令";
            this.TabSheet1.Enabled = true;
            this.TabSheet1.Name = "TabSheet1";
            ((System.ComponentModel.ISupportInitialize)(this.StringGridGameCmd)).BeginInit();
            this.StringGridGameCmd.Size  = new System.Drawing.Size(639, 265);
            this.StringGridGameCmd.Location  = new System.Drawing.Point(2, 8);
            //this.StringGridGameCmd.Click += new System.EventHandler(this.StringGridGameCmdClick);
            this.StringGridGameCmd.Name = "StringGridGameCmd";
            this.StringGridGameCmd.Enabled = true;
//            this.StringGridGameCmd.PreferredColumnWidth = (int){107, 76, 190, 248};
            this.StringGridGameCmd.TabIndex = 0;
            this.GroupBox1.Size  = new System.Drawing.Size(639, 89);
            this.GroupBox1.Location  = new System.Drawing.Point(2, 280);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.Text = "命令设置";
            this.GroupBox1.TabIndex = 1;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.Label1.Size  = new System.Drawing.Size(54, 12);
            this.Label1.Location  = new System.Drawing.Point(8, 20);
            this.Label1.Text = "命令名称:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label6.Size  = new System.Drawing.Size(54, 12);
            this.Label6.Location  = new System.Drawing.Point(176, 18);
            this.Label6.Text = "所需权限:";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.LabelUserCmdFunc.Size  = new System.Drawing.Size(401, 12);
            this.LabelUserCmdFunc.Location  = new System.Drawing.Point(64, 44);
            this.LabelUserCmdFunc.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.LabelUserCmdFunc.AutoSize = false;
            this.LabelUserCmdFunc.Enabled = true;
            this.LabelUserCmdFunc.Name = "LabelUserCmdFunc";
            this.LabelUserCmdParam.Size  = new System.Drawing.Size(401, 12);
            this.LabelUserCmdParam.Location  = new System.Drawing.Point(64, 68);
            this.LabelUserCmdParam.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.LabelUserCmdParam.AutoSize = false;
            this.LabelUserCmdParam.Enabled = true;
            this.LabelUserCmdParam.Name = "LabelUserCmdParam";
            this.Label2.Size  = new System.Drawing.Size(54, 12);
            this.Label2.Location  = new System.Drawing.Point(8, 44);
            this.Label2.Text = "命令功能:";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label3.Size  = new System.Drawing.Size(54, 12);
            this.Label3.Location  = new System.Drawing.Point(8, 68);
            this.Label3.Text = "命令格式:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.EditUserCmdName.Size  = new System.Drawing.Size(105, 20);
            this.EditUserCmdName.Location  = new System.Drawing.Point(64, 16);
            this.EditUserCmdName.TabIndex = 0;
            //this.EditUserCmdName.ModifiedChanged += new System.EventHandler(this.EditUserCmdNameChange);
            this.EditUserCmdName.Enabled = true;
            this.EditUserCmdName.Name = "EditUserCmdName";
            ((System.ComponentModel.ISupportInitialize)(this.EditUserCmdPerMission)).BeginInit();
            this.EditUserCmdPerMission.Size  = new System.Drawing.Size(45, 21);
            this.EditUserCmdPerMission.Location  = new System.Drawing.Point(236, 15);
            this.EditUserCmdPerMission.Value = 10;
            this.EditUserCmdPerMission.TabIndex = 1;
            this.EditUserCmdPerMission.Name = "EditUserCmdPerMission";
            this.EditUserCmdPerMission.Enabled = true;
            this.EditUserCmdOK.Size  = new System.Drawing.Size(65, 25);
            this.EditUserCmdOK.Location  = new System.Drawing.Point(560, 16);
            //this.EditUserCmdOK.Click += new System.EventHandler(this.EditUserCmdOKClick);
            this.EditUserCmdOK.TabIndex = 2;
            this.EditUserCmdOK.Name = "EditUserCmdOK";
            this.EditUserCmdOK.Enabled = true;
            this.EditUserCmdOK.Text = "确定(&O)";
            this.EditUserCmdSave.Size  = new System.Drawing.Size(65, 25);
            this.EditUserCmdSave.Location  = new System.Drawing.Point(560, 56);
            //this.EditUserCmdSave.Click += new System.EventHandler(this.EditUserCmdSaveClick);
            this.EditUserCmdSave.TabIndex = 3;
            this.EditUserCmdSave.Name = "EditUserCmdSave";
            this.EditUserCmdSave.Enabled = true;
            this.EditUserCmdSave.Text = "保存(&S)";
            this.TabSheet2.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet2.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet2.SuspendLayout();
            this.TabSheet2.Text = "管理命令";
            this.TabSheet2.ImageIndex = 1;
            this.TabSheet2.Enabled = true;
            this.TabSheet2.Name = "TabSheet2";
            ((System.ComponentModel.ISupportInitialize)(this.StringGridGameMasterCmd)).BeginInit();
            this.StringGridGameMasterCmd.Size  = new System.Drawing.Size(639, 257);
            this.StringGridGameMasterCmd.Location  = new System.Drawing.Point(2, 8);
            //this.StringGridGameMasterCmd.Click += new System.EventHandler(this.StringGridGameMasterCmdClick);
            this.StringGridGameMasterCmd.Name = "StringGridGameMasterCmd";
            this.StringGridGameMasterCmd.Enabled = true;
//            this.StringGridGameMasterCmd.PreferredColumnWidth = (int){119, 83, 161, 248};
            this.StringGridGameMasterCmd.TabIndex = 0;
            this.GroupBox2.Size  = new System.Drawing.Size(631, 89);
            this.GroupBox2.Location  = new System.Drawing.Point(10, 272);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.Text = "命令设置";
            this.GroupBox2.TabIndex = 1;
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label4.Size  = new System.Drawing.Size(54, 12);
            this.Label4.Location  = new System.Drawing.Point(8, 20);
            this.Label4.Text = "命令名称:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label5.Size  = new System.Drawing.Size(54, 12);
            this.Label5.Location  = new System.Drawing.Point(176, 18);
            this.Label5.Text = "所需权限:";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.LabelGameMasterCmdFunc.Size  = new System.Drawing.Size(401, 12);
            this.LabelGameMasterCmdFunc.Location  = new System.Drawing.Point(64, 44);
            this.LabelGameMasterCmdFunc.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.LabelGameMasterCmdFunc.AutoSize = false;
            this.LabelGameMasterCmdFunc.Enabled = true;
            this.LabelGameMasterCmdFunc.Name = "LabelGameMasterCmdFunc";
            this.LabelGameMasterCmdParam.Size  = new System.Drawing.Size(401, 12);
            this.LabelGameMasterCmdParam.Location  = new System.Drawing.Point(64, 68);
            this.LabelGameMasterCmdParam.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.LabelGameMasterCmdParam.AutoSize = false;
            this.LabelGameMasterCmdParam.Enabled = true;
            this.LabelGameMasterCmdParam.Name = "LabelGameMasterCmdParam";
            this.Label7.Size  = new System.Drawing.Size(54, 12);
            this.Label7.Location  = new System.Drawing.Point(8, 44);
            this.Label7.Text = "命令功能:";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label8.Size  = new System.Drawing.Size(54, 12);
            this.Label8.Location  = new System.Drawing.Point(8, 68);
            this.Label8.Text = "命令格式:";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.EditGameMasterCmdName.Size  = new System.Drawing.Size(105, 20);
            this.EditGameMasterCmdName.Location  = new System.Drawing.Point(64, 16);
            this.EditGameMasterCmdName.TabIndex = 0;
            //this.EditGameMasterCmdName.ModifiedChanged += new System.EventHandler(this.EditGameMasterCmdNameChange);
            this.EditGameMasterCmdName.Enabled = true;
            this.EditGameMasterCmdName.Name = "EditGameMasterCmdName";
            ((System.ComponentModel.ISupportInitialize)(this.EditGameMasterCmdPerMission)).BeginInit();
            this.EditGameMasterCmdPerMission.Size  = new System.Drawing.Size(45, 21);
            this.EditGameMasterCmdPerMission.Location  = new System.Drawing.Point(236, 15);
            this.EditGameMasterCmdPerMission.Value = 10;
            this.EditGameMasterCmdPerMission.TabIndex = 1;
            this.EditGameMasterCmdPerMission.Name = "EditGameMasterCmdPerMission";
            this.EditGameMasterCmdPerMission.Enabled = true;
            this.EditGameMasterCmdOK.Size  = new System.Drawing.Size(65, 25);
            this.EditGameMasterCmdOK.Location  = new System.Drawing.Point(552, 16);
            //this.EditGameMasterCmdOK.Click += new System.EventHandler(this.EditGameMasterCmdOKClick);
            this.EditGameMasterCmdOK.TabIndex = 2;
            this.EditGameMasterCmdOK.Name = "EditGameMasterCmdOK";
            this.EditGameMasterCmdOK.Enabled = true;
            this.EditGameMasterCmdOK.Text = "确定(&O)";
            this.EditGameMasterCmdSave.Size  = new System.Drawing.Size(65, 25);
            this.EditGameMasterCmdSave.Location  = new System.Drawing.Point(552, 56);
            //this.EditGameMasterCmdSave.Click += new System.EventHandler(this.EditGameMasterCmdSaveClick);
            this.EditGameMasterCmdSave.TabIndex = 3;
            this.EditGameMasterCmdSave.Name = "EditGameMasterCmdSave";
            this.EditGameMasterCmdSave.Enabled = true;
            this.EditGameMasterCmdSave.Text = "保存(&S)";
            this.TabSheet3.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet3.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet3.SuspendLayout();
            this.TabSheet3.Text = "调试命令";
            this.TabSheet3.ImageIndex = 2;
            this.TabSheet3.Enabled = true;
            this.TabSheet3.Name = "TabSheet3";
            ((System.ComponentModel.ISupportInitialize)(this.StringGridGameDebugCmd)).BeginInit();
            this.StringGridGameDebugCmd.Size  = new System.Drawing.Size(639, 265);
            this.StringGridGameDebugCmd.Location  = new System.Drawing.Point(2, 8);
            //this.StringGridGameDebugCmd.Click += new System.EventHandler(this.StringGridGameDebugCmdClick);
            this.StringGridGameDebugCmd.Name = "StringGridGameDebugCmd";
            this.StringGridGameDebugCmd.Enabled = true;
//            this.StringGridGameDebugCmd.PreferredColumnWidth = (int){109, 81, 183, 248};
            this.StringGridGameDebugCmd.TabIndex = 0;
            this.GroupBox3.Size  = new System.Drawing.Size(639, 89);
            this.GroupBox3.Location  = new System.Drawing.Point(2, 280);
            this.GroupBox3.SuspendLayout();
            this.GroupBox3.Text = "命令设置";
            this.GroupBox3.TabIndex = 1;
            this.GroupBox3.Enabled = true;
            this.GroupBox3.Name = "GroupBox3";
            this.Label9.Size  = new System.Drawing.Size(54, 12);
            this.Label9.Location  = new System.Drawing.Point(8, 20);
            this.Label9.Text = "命令名称:";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label10.Size  = new System.Drawing.Size(54, 12);
            this.Label10.Location  = new System.Drawing.Point(176, 18);
            this.Label10.Text = "所需权限:";
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.LabelGameDebugCmdFunc.Size  = new System.Drawing.Size(401, 12);
            this.LabelGameDebugCmdFunc.Location  = new System.Drawing.Point(64, 44);
            this.LabelGameDebugCmdFunc.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.LabelGameDebugCmdFunc.AutoSize = false;
            this.LabelGameDebugCmdFunc.Enabled = true;
            this.LabelGameDebugCmdFunc.Name = "LabelGameDebugCmdFunc";
            this.LabelGameDebugCmdParam.Size  = new System.Drawing.Size(401, 12);
            this.LabelGameDebugCmdParam.Location  = new System.Drawing.Point(64, 68);
            this.LabelGameDebugCmdParam.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.LabelGameDebugCmdParam.AutoSize = false;
            this.LabelGameDebugCmdParam.Enabled = true;
            this.LabelGameDebugCmdParam.Name = "LabelGameDebugCmdParam";
            this.Label11.Size  = new System.Drawing.Size(54, 12);
            this.Label11.Location  = new System.Drawing.Point(8, 44);
            this.Label11.Text = "命令功能:";
            this.Label11.Enabled = true;
            this.Label11.Name = "Label11";
            this.Label12.Size  = new System.Drawing.Size(54, 12);
            this.Label12.Location  = new System.Drawing.Point(8, 68);
            this.Label12.Text = "命令格式:";
            this.Label12.Enabled = true;
            this.Label12.Name = "Label12";
            this.EditGameDebugCmdName.Size  = new System.Drawing.Size(105, 20);
            this.EditGameDebugCmdName.Location  = new System.Drawing.Point(64, 16);
            this.EditGameDebugCmdName.TabIndex = 0;
            //this.EditGameDebugCmdName.ModifiedChanged += new System.EventHandler(this.EditGameDebugCmdNameChange);
            this.EditGameDebugCmdName.Enabled = true;
            this.EditGameDebugCmdName.Name = "EditGameDebugCmdName";
            ((System.ComponentModel.ISupportInitialize)(this.EditGameDebugCmdPerMission)).BeginInit();
            this.EditGameDebugCmdPerMission.Size  = new System.Drawing.Size(45, 21);
            this.EditGameDebugCmdPerMission.Location  = new System.Drawing.Point(236, 15);
            this.EditGameDebugCmdPerMission.Value = 10;
            this.EditGameDebugCmdPerMission.TabIndex = 1;
            this.EditGameDebugCmdPerMission.Name = "EditGameDebugCmdPerMission";
            this.EditGameDebugCmdPerMission.Enabled = true;
            this.EditGameDebugCmdOK.Size  = new System.Drawing.Size(65, 25);
            this.EditGameDebugCmdOK.Location  = new System.Drawing.Point(560, 16);
            //this.EditGameDebugCmdOK.Click += new System.EventHandler(this.EditGameDebugCmdOKClick);
            this.EditGameDebugCmdOK.TabIndex = 2;
            this.EditGameDebugCmdOK.Name = "EditGameDebugCmdOK";
            this.EditGameDebugCmdOK.Enabled = true;
            this.EditGameDebugCmdOK.Text = "确定(&O)";
            this.EditGameDebugCmdSave.Size  = new System.Drawing.Size(65, 25);
            this.EditGameDebugCmdSave.Location  = new System.Drawing.Point(560, 56);
            //this.EditGameDebugCmdSave.Click += new System.EventHandler(this.EditGameDebugCmdSaveClick);
            this.EditGameDebugCmdSave.TabIndex = 3;
            this.EditGameDebugCmdSave.Name = "EditGameDebugCmdSave";
            this.EditGameDebugCmdSave.Enabled = true;
            this.EditGameDebugCmdSave.Text = "保存(&S)";
            this.GroupBox1.Controls.Add(Label1);
            this.GroupBox1.Controls.Add(Label6);
            this.GroupBox1.Controls.Add(LabelUserCmdFunc);
            this.GroupBox1.Controls.Add(LabelUserCmdParam);
            this.GroupBox1.Controls.Add(Label2);
            this.GroupBox1.Controls.Add(Label3);
            this.GroupBox1.Controls.Add(EditUserCmdName);
            this.GroupBox1.Controls.Add(EditUserCmdPerMission);
            this.GroupBox1.Controls.Add(EditUserCmdOK);
            this.GroupBox1.Controls.Add(EditUserCmdSave);
            ((System.ComponentModel.ISupportInitialize)(this.EditUserCmdPerMission)).EndInit();
            this.GroupBox1.ResumeLayout(false);
            this.TabSheet1.Controls.Add(StringGridGameCmd);
            this.TabSheet1.Controls.Add(GroupBox1);
            ((System.ComponentModel.ISupportInitialize)(this.StringGridGameCmd)).EndInit();
            this.TabSheet1.ResumeLayout(false);
            this.GroupBox2.Controls.Add(Label4);
            this.GroupBox2.Controls.Add(Label5);
            this.GroupBox2.Controls.Add(LabelGameMasterCmdFunc);
            this.GroupBox2.Controls.Add(LabelGameMasterCmdParam);
            this.GroupBox2.Controls.Add(Label7);
            this.GroupBox2.Controls.Add(Label8);
            this.GroupBox2.Controls.Add(EditGameMasterCmdName);
            this.GroupBox2.Controls.Add(EditGameMasterCmdPerMission);
            this.GroupBox2.Controls.Add(EditGameMasterCmdOK);
            this.GroupBox2.Controls.Add(EditGameMasterCmdSave);
            ((System.ComponentModel.ISupportInitialize)(this.EditGameMasterCmdPerMission)).EndInit();
            this.GroupBox2.ResumeLayout(false);
            this.TabSheet2.Controls.Add(StringGridGameMasterCmd);
            this.TabSheet2.Controls.Add(GroupBox2);
            ((System.ComponentModel.ISupportInitialize)(this.StringGridGameMasterCmd)).EndInit();
            this.TabSheet2.ResumeLayout(false);
            this.GroupBox3.Controls.Add(Label9);
            this.GroupBox3.Controls.Add(Label10);
            this.GroupBox3.Controls.Add(LabelGameDebugCmdFunc);
            this.GroupBox3.Controls.Add(LabelGameDebugCmdParam);
            this.GroupBox3.Controls.Add(Label11);
            this.GroupBox3.Controls.Add(Label12);
            this.GroupBox3.Controls.Add(EditGameDebugCmdName);
            this.GroupBox3.Controls.Add(EditGameDebugCmdPerMission);
            this.GroupBox3.Controls.Add(EditGameDebugCmdOK);
            this.GroupBox3.Controls.Add(EditGameDebugCmdSave);
            ((System.ComponentModel.ISupportInitialize)(this.EditGameDebugCmdPerMission)).EndInit();
            this.GroupBox3.ResumeLayout(false);
            this.TabSheet3.Controls.Add(StringGridGameDebugCmd);
            this.TabSheet3.Controls.Add(GroupBox3);
            ((System.ComponentModel.ISupportInitialize)(this.StringGridGameDebugCmd)).EndInit();
            this.TabSheet3.ResumeLayout(false);
            this.PageControl.Controls.Add(TabSheet1);
            this.PageControl.Controls.Add(TabSheet2);
            this.PageControl.Controls.Add(TabSheet3);
            this.PageControl.ResumeLayout(false);
            this.Controls.Add(PageControl);
            this.ResumeLayout(false);
        }
#endregion

    }
}
