namespace LoginSrv
{
  partial class TFrmBasicSet
    {
        public System.Windows.Forms.TabControl PageControl1;
        public System.Windows.Forms.TabPage TabSheet1;
        public System.Windows.Forms.GroupBox GroupBox1;
        public System.Windows.Forms.CheckBox CheckBoxTestServer;
        public System.Windows.Forms.CheckBox CheckBoxEnableMakingID;
        public System.Windows.Forms.CheckBox CheckBoxEnableGetbackPassword;
        public System.Windows.Forms.GroupBox GroupBox2;
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.CheckBox CheckBoxAutoClear;
        public System.Windows.Forms.NumericUpDown SpinEditAutoClearTime;
        public System.Windows.Forms.Button ButtonRestoreBasic;
        public System.Windows.Forms.GroupBox GroupBox7;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.CheckBox CheckBoxAutoUnLockAccount;
        public System.Windows.Forms.NumericUpDown SpinEditUnLockAccountTime;
        public System.Windows.Forms.CheckBox CheckBoxMinimize;
        public System.Windows.Forms.TabPage TabSheet2;
        public System.Windows.Forms.Button ButtonRestoreNet;
        public System.Windows.Forms.GroupBox GroupBox3;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.TextBox EditGateAddr;
        public System.Windows.Forms.TextBox EditGatePort;
        public System.Windows.Forms.GroupBox GroupBox4;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.TextBox EditMonAddr;
        public System.Windows.Forms.TextBox EditMonPort;
        public System.Windows.Forms.GroupBox GroupBox5;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.TextBox EditServerAddr;
        public System.Windows.Forms.TextBox EditServerPort;
        public System.Windows.Forms.GroupBox GroupBox6;
        public System.Windows.Forms.CheckBox CheckBoxDynamicIPMode;
        public System.Windows.Forms.TabPage TabSheet3;
        public System.Windows.Forms.Button ButtonSave;
        public System.Windows.Forms.Button ButtonClose;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        public void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.PageControl1 = new System.Windows.Forms.TabControl();
            this.TabSheet1 = new System.Windows.Forms.TabPage();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.CheckBoxTestServer = new System.Windows.Forms.CheckBox();
            this.CheckBoxEnableMakingID = new System.Windows.Forms.CheckBox();
            this.CheckBoxEnableGetbackPassword = new System.Windows.Forms.CheckBox();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.CheckBoxAutoClear = new System.Windows.Forms.CheckBox();
            this.SpinEditAutoClearTime = new System.Windows.Forms.NumericUpDown();
            this.ButtonRestoreBasic = new System.Windows.Forms.Button();
            this.GroupBox7 = new System.Windows.Forms.GroupBox();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.CheckBoxAutoUnLockAccount = new System.Windows.Forms.CheckBox();
            this.SpinEditUnLockAccountTime = new System.Windows.Forms.NumericUpDown();
            this.CheckBoxMinimize = new System.Windows.Forms.CheckBox();
            this.TabSheet2 = new System.Windows.Forms.TabPage();
            this.ButtonRestoreNet = new System.Windows.Forms.Button();
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.EditGateAddr = new System.Windows.Forms.TextBox();
            this.EditGatePort = new System.Windows.Forms.TextBox();
            this.GroupBox4 = new System.Windows.Forms.GroupBox();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.EditMonAddr = new System.Windows.Forms.TextBox();
            this.EditMonPort = new System.Windows.Forms.TextBox();
            this.GroupBox5 = new System.Windows.Forms.GroupBox();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.EditServerAddr = new System.Windows.Forms.TextBox();
            this.EditServerPort = new System.Windows.Forms.TextBox();
            this.GroupBox6 = new System.Windows.Forms.GroupBox();
            this.CheckBoxDynamicIPMode = new System.Windows.Forms.CheckBox();
            this.TabSheet3 = new System.Windows.Forms.TabPage();
            this.ButtonSave = new System.Windows.Forms.Button();
            this.ButtonClose = new System.Windows.Forms.Button();
            //this.SuspendLayout();
            //this.Location  = new System.Drawing.Point(570, 319);
            //this.ClientSize  = new System.Drawing.Size(419, 240);
            //this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(134)));
            //this.AutoScroll = true;
            //this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            //this.Name = "FrmBasicSet";
            //this.Text = "基本设置";
            //this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.PageControl1.Size  = new System.Drawing.Size(401, 193);
            this.PageControl1.Location  = new System.Drawing.Point(8, 8);
            this.PageControl1.SuspendLayout();
            this.PageControl1.SelectedTab = TabSheet1;
            this.PageControl1.TabIndex = 0;
            this.PageControl1.Enabled = true;
            this.PageControl1.Name = "PageControl1";
            this.TabSheet1.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet1.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet1.SuspendLayout();
            this.TabSheet1.Text = "普通设置";
            this.TabSheet1.Enabled = true;
            this.TabSheet1.Name = "TabSheet1";
            this.GroupBox1.Size  = new System.Drawing.Size(177, 73);
            this.GroupBox1.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.Text = "功能设置";
            this.GroupBox1.TabIndex = 0;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.CheckBoxTestServer.Size  = new System.Drawing.Size(97, 17);
            this.CheckBoxTestServer.Location  = new System.Drawing.Point(16, 16);
            this.CheckBoxTestServer.Text = "测试模式";
            this.CheckBoxTestServer.TabIndex = 0;
            this.CheckBoxTestServer.Enabled = true;
          //  this.CheckBoxTestServer.Click += new System.EventHandler(this.CheckBoxTestServerClick);
            this.CheckBoxTestServer.Name = "CheckBoxTestServer";
            this.CheckBoxEnableMakingID.Size  = new System.Drawing.Size(97, 17);
            this.CheckBoxEnableMakingID.Location  = new System.Drawing.Point(16, 32);
            this.CheckBoxEnableMakingID.Text = "允许创建账号";
            this.CheckBoxEnableMakingID.TabIndex = 1;
            this.CheckBoxEnableMakingID.Enabled = true;
         //   this.CheckBoxEnableMakingID.Click += new System.EventHandler(this.CheckBoxEnableMakingIDClick);
            this.CheckBoxEnableMakingID.Name = "CheckBoxEnableMakingID";
            this.CheckBoxEnableGetbackPassword.Size  = new System.Drawing.Size(97, 17);
            this.CheckBoxEnableGetbackPassword.Location  = new System.Drawing.Point(16, 48);
            this.CheckBoxEnableGetbackPassword.Text = "允许取回密码";
            this.CheckBoxEnableGetbackPassword.TabIndex = 2;
            this.CheckBoxEnableGetbackPassword.Enabled = true;
          //  this.CheckBoxEnableGetbackPassword.Click += new System.EventHandler(this.CheckBoxEnableGetbackPasswordClick);
            this.CheckBoxEnableGetbackPassword.Name = "CheckBoxEnableGetbackPassword";
            this.GroupBox2.Size  = new System.Drawing.Size(185, 73);
            this.GroupBox2.Location  = new System.Drawing.Point(200, 8);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.Text = "清理账号设置";
            this.GroupBox2.TabIndex = 1;
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label1.Size  = new System.Drawing.Size(54, 12);
            this.Label1.Location  = new System.Drawing.Point(16, 40);
            this.Label1.Text = "清理间隔:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label2.Size  = new System.Drawing.Size(12, 12);
            this.Label2.Location  = new System.Drawing.Point(144, 40);
            this.Label2.Text = "秒";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.CheckBoxAutoClear.Size  = new System.Drawing.Size(97, 17);
            this.CheckBoxAutoClear.Location  = new System.Drawing.Point(16, 16);
            this.CheckBoxAutoClear.Text = "自动清理账号";
            this.CheckBoxAutoClear.TabIndex = 0;
            this.CheckBoxAutoClear.Enabled = true;
          //  this.CheckBoxAutoClear.Click += new System.EventHandler(this.CheckBoxAutoClearClick);
            this.CheckBoxAutoClear.Name = "CheckBoxAutoClear";
            ((System.ComponentModel.ISupportInitialize)(this.SpinEditAutoClearTime)).BeginInit();
            this.SpinEditAutoClearTime.Size  = new System.Drawing.Size(65, 21);
            this.SpinEditAutoClearTime.Location  = new System.Drawing.Point(72, 36);
            this.SpinEditAutoClearTime.Value = 1;
            this.SpinEditAutoClearTime.TabIndex = 1;
            this.SpinEditAutoClearTime.Name = "SpinEditAutoClearTime";
            this.SpinEditAutoClearTime.Enabled = true;
            this.ButtonRestoreBasic.Size  = new System.Drawing.Size(67, 25);
            this.ButtonRestoreBasic.Location  = new System.Drawing.Point(320, 136);
          //  this.ButtonRestoreBasic.Click += new System.EventHandler(this.ButtonRestoreBasicClick);
            this.ButtonRestoreBasic.TabIndex = 2;
            this.ButtonRestoreBasic.Name = "ButtonRestoreBasic";
            this.ButtonRestoreBasic.Enabled = true;
            this.ButtonRestoreBasic.Text = "默认(&D)";
            this.ButtonRestoreBasic.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.GroupBox7.Size  = new System.Drawing.Size(177, 65);
            this.GroupBox7.Location  = new System.Drawing.Point(8, 88);
            this.GroupBox7.SuspendLayout();
            this.GroupBox7.Text = "自动解除锁定账号";
            this.GroupBox7.TabIndex = 3;
            this.GroupBox7.Enabled = true;
            this.GroupBox7.Name = "GroupBox7";
            this.Label9.Size  = new System.Drawing.Size(78, 12);
            this.Label9.Location  = new System.Drawing.Point(8, 40);
            this.Label9.Text = "解除等待时间:";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label10.Size  = new System.Drawing.Size(12, 12);
            this.Label10.Location  = new System.Drawing.Point(160, 40);
            this.Label10.Text = "分";
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.CheckBoxAutoUnLockAccount.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxAutoUnLockAccount.Location  = new System.Drawing.Point(8, 16);
            this.CheckBoxAutoUnLockAccount.Text = "自动解除锁定账号";
            this.CheckBoxAutoUnLockAccount.TabIndex = 0;
            this.CheckBoxAutoUnLockAccount.Enabled = true;
           // this.CheckBoxAutoUnLockAccount.Click += new System.EventHandler(this.CheckBoxAutoUnLockAccountClick);
            this.CheckBoxAutoUnLockAccount.Name = "CheckBoxAutoUnLockAccount";
            ((System.ComponentModel.ISupportInitialize)(this.SpinEditUnLockAccountTime)).BeginInit();
            this.SpinEditUnLockAccountTime.Size  = new System.Drawing.Size(65, 21);
            this.SpinEditUnLockAccountTime.Location  = new System.Drawing.Point(88, 36);
            this.SpinEditUnLockAccountTime.Value = 1;
            this.SpinEditUnLockAccountTime.TabIndex = 1;
            this.SpinEditUnLockAccountTime.Name = "SpinEditUnLockAccountTime";
            this.SpinEditUnLockAccountTime.Enabled = true;
            this.CheckBoxMinimize.Size  = new System.Drawing.Size(121, 17);
            this.CheckBoxMinimize.Location  = new System.Drawing.Point(200, 136);
            this.CheckBoxMinimize.Text = "启动成功后最小化";
            this.CheckBoxMinimize.TabIndex = 4;
            this.CheckBoxMinimize.Enabled = true;
           // this.CheckBoxMinimize.Click += new System.EventHandler(this.CheckBoxMinimizeClick);
            this.CheckBoxMinimize.Name = "CheckBoxMinimize";
            this.TabSheet2.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet2.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet2.SuspendLayout();
            this.TabSheet2.Text = "网络设置";
            this.TabSheet2.ImageIndex = 1;
            this.TabSheet2.Enabled = true;
            this.TabSheet2.Name = "TabSheet2";
            this.ButtonRestoreNet.Size  = new System.Drawing.Size(67, 25);
            this.ButtonRestoreNet.Location  = new System.Drawing.Point(320, 136);
           // this.ButtonRestoreNet.Click += new System.EventHandler(this.ButtonRestoreNetClick);
            this.ButtonRestoreNet.TabIndex = 0;
            this.ButtonRestoreNet.Name = "ButtonRestoreNet";
            this.ButtonRestoreNet.Enabled = true;
            this.ButtonRestoreNet.Text = "默认(&D)";
            this.ButtonRestoreNet.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.GroupBox3.Size  = new System.Drawing.Size(185, 65);
            this.GroupBox3.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox3.SuspendLayout();
            this.GroupBox3.Text = "网关设置";
            this.GroupBox3.TabIndex = 1;
            this.GroupBox3.Enabled = true;
            this.GroupBox3.Name = "GroupBox3";
            this.Label3.Size  = new System.Drawing.Size(54, 12);
            this.Label3.Location  = new System.Drawing.Point(8, 18);
            this.Label3.Text = "绑定地址:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label4.Size  = new System.Drawing.Size(54, 12);
            this.Label4.Location  = new System.Drawing.Point(8, 42);
            this.Label4.Text = "网关端口:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.EditGateAddr.Size  = new System.Drawing.Size(105, 20);
            this.EditGateAddr.Location  = new System.Drawing.Point(72, 14);
            this.EditGateAddr.TabIndex = 0;
          //  this.EditGateAddr.ModifiedChanged += new System.EventHandler(this.EditGateAddrChange);
            this.EditGateAddr.Enabled = true;
            this.EditGateAddr.Name = "EditGateAddr";
            this.EditGatePort.Size  = new System.Drawing.Size(57, 20);
            this.EditGatePort.Location  = new System.Drawing.Point(72, 38);
            this.EditGatePort.TabIndex = 1;
           // this.EditGatePort.ModifiedChanged += new System.EventHandler(this.EditGatePortChange);
            this.EditGatePort.Enabled = true;
            this.EditGatePort.Name = "EditGatePort";
            this.GroupBox4.Size  = new System.Drawing.Size(185, 65);
            this.GroupBox4.Location  = new System.Drawing.Point(200, 8);
            this.GroupBox4.SuspendLayout();
            this.GroupBox4.Text = "远程监控设置";
            this.GroupBox4.TabIndex = 2;
            this.GroupBox4.Enabled = true;
            this.GroupBox4.Name = "GroupBox4";
            this.Label5.Size  = new System.Drawing.Size(54, 12);
            this.Label5.Location  = new System.Drawing.Point(8, 18);
            this.Label5.Text = "绑定地址:";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label6.Size  = new System.Drawing.Size(54, 12);
            this.Label6.Location  = new System.Drawing.Point(8, 42);
            this.Label6.Text = "网关端口:";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.EditMonAddr.Size  = new System.Drawing.Size(105, 20);
            this.EditMonAddr.Location  = new System.Drawing.Point(72, 14);
            this.EditMonAddr.TabIndex = 0;
           // this.EditMonAddr.ModifiedChanged += new System.EventHandler(this.EditMonAddrChange);
            this.EditMonAddr.Enabled = true;
            this.EditMonAddr.Name = "EditMonAddr";
            this.EditMonPort.Size  = new System.Drawing.Size(57, 20);
            this.EditMonPort.Location  = new System.Drawing.Point(72, 38);
            this.EditMonPort.TabIndex = 1;
           // this.EditMonPort.ModifiedChanged += new System.EventHandler(this.EditMonPortChange);
            this.EditMonPort.Enabled = true;
            this.EditMonPort.Name = "EditMonPort";
            this.GroupBox5.Size  = new System.Drawing.Size(185, 65);
            this.GroupBox5.Location  = new System.Drawing.Point(8, 88);
            this.GroupBox5.SuspendLayout();
            this.GroupBox5.Text = "服务器网络设置";
            this.GroupBox5.TabIndex = 3;
            this.GroupBox5.Enabled = true;
            this.GroupBox5.Name = "GroupBox5";
            this.Label7.Size  = new System.Drawing.Size(54, 12);
            this.Label7.Location  = new System.Drawing.Point(8, 18);
            this.Label7.Text = "绑定地址:";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label8.Size  = new System.Drawing.Size(54, 12);
            this.Label8.Location  = new System.Drawing.Point(8, 42);
            this.Label8.Text = "使用端口:";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.EditServerAddr.Size  = new System.Drawing.Size(105, 20);
            this.EditServerAddr.Location  = new System.Drawing.Point(72, 14);
            this.EditServerAddr.TabIndex = 0;
            //this.EditServerAddr.ModifiedChanged += new System.EventHandler(this.EditServerAddrChange);
            this.EditServerAddr.Enabled = true;
            this.EditServerAddr.Name = "EditServerAddr";
            this.EditServerPort.Size  = new System.Drawing.Size(57, 20);
            this.EditServerPort.Location  = new System.Drawing.Point(72, 38);
            this.EditServerPort.TabIndex = 1;
           // this.EditServerPort.ModifiedChanged += new System.EventHandler(this.EditServerPortChange);
            this.EditServerPort.Enabled = true;
            this.EditServerPort.Name = "EditServerPort";
            this.GroupBox6.Size  = new System.Drawing.Size(113, 41);
            this.GroupBox6.Location  = new System.Drawing.Point(200, 88);
            this.GroupBox6.SuspendLayout();
            this.GroupBox6.Text = "动态域名模式";
            this.GroupBox6.TabIndex = 4;
            this.GroupBox6.Enabled = true;
            this.GroupBox6.Name = "GroupBox6";
            this.CheckBoxDynamicIPMode.Size  = new System.Drawing.Size(73, 17);
            this.CheckBoxDynamicIPMode.Location  = new System.Drawing.Point(16, 16);
            this.CheckBoxDynamicIPMode.Text = "动态域名";
            this.CheckBoxDynamicIPMode.TabIndex = 0;
            this.CheckBoxDynamicIPMode.Enabled = true;
            //this.CheckBoxDynamicIPMode.Click += new System.EventHandler(this.CheckBoxDynamicIPModeClick);
            this.CheckBoxDynamicIPMode.Name = "CheckBoxDynamicIPMode";
            this.TabSheet3.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet3.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet3.Text = "目录设置";
            this.TabSheet3.ImageIndex = 2;
            this.TabSheet3.Enabled = true;
            this.TabSheet3.Name = "TabSheet3";
            this.ButtonSave.Size  = new System.Drawing.Size(75, 25);
            this.ButtonSave.Location  = new System.Drawing.Point(248, 208);
            //this.ButtonSave.Click += new System.EventHandler(this.ButtonSaveClick);
            this.ButtonSave.TabIndex = 1;
            this.ButtonSave.Name = "ButtonSave";
            this.ButtonSave.Enabled = true;
            this.ButtonSave.Text = "保存(&S)";
            this.ButtonSave.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ButtonClose.Size  = new System.Drawing.Size(75, 25);
            this.ButtonClose.Location  = new System.Drawing.Point(334, 208);
            //this.ButtonClose.Click += new System.EventHandler(this.ButtonCloseClick);
            this.ButtonClose.TabIndex = 2;
            this.ButtonClose.Name = "ButtonClose";
            this.ButtonClose.Enabled = true;
            this.ButtonClose.Text = "确定(&O)";
            this.ButtonClose.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.GroupBox1.Controls.Add(CheckBoxTestServer);
            this.GroupBox1.Controls.Add(CheckBoxEnableMakingID);
            this.GroupBox1.Controls.Add(CheckBoxEnableGetbackPassword);
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox2.Controls.Add(Label1);
            this.GroupBox2.Controls.Add(Label2);
            this.GroupBox2.Controls.Add(CheckBoxAutoClear);
            this.GroupBox2.Controls.Add(SpinEditAutoClearTime);
            ((System.ComponentModel.ISupportInitialize)(this.SpinEditAutoClearTime)).EndInit();
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox7.Controls.Add(Label9);
            this.GroupBox7.Controls.Add(Label10);
            this.GroupBox7.Controls.Add(CheckBoxAutoUnLockAccount);
            this.GroupBox7.Controls.Add(SpinEditUnLockAccountTime);
            ((System.ComponentModel.ISupportInitialize)(this.SpinEditUnLockAccountTime)).EndInit();
            this.GroupBox7.ResumeLayout(false);
            this.TabSheet1.Controls.Add(GroupBox1);
            this.TabSheet1.Controls.Add(GroupBox2);
            this.TabSheet1.Controls.Add(ButtonRestoreBasic);
            this.TabSheet1.Controls.Add(GroupBox7);
            this.TabSheet1.Controls.Add(CheckBoxMinimize);
            this.TabSheet1.ResumeLayout(false);
            this.GroupBox3.Controls.Add(Label3);
            this.GroupBox3.Controls.Add(Label4);
            this.GroupBox3.Controls.Add(EditGateAddr);
            this.GroupBox3.Controls.Add(EditGatePort);
            this.GroupBox3.ResumeLayout(false);
            this.GroupBox4.Controls.Add(Label5);
            this.GroupBox4.Controls.Add(Label6);
            this.GroupBox4.Controls.Add(EditMonAddr);
            this.GroupBox4.Controls.Add(EditMonPort);
            this.GroupBox4.ResumeLayout(false);
            this.GroupBox5.Controls.Add(Label7);
            this.GroupBox5.Controls.Add(Label8);
            this.GroupBox5.Controls.Add(EditServerAddr);
            this.GroupBox5.Controls.Add(EditServerPort);
            this.GroupBox5.ResumeLayout(false);
            this.GroupBox6.Controls.Add(CheckBoxDynamicIPMode);
            this.GroupBox6.ResumeLayout(false);
            this.TabSheet2.Controls.Add(ButtonRestoreNet);
            this.TabSheet2.Controls.Add(GroupBox3);
            this.TabSheet2.Controls.Add(GroupBox4);
            this.TabSheet2.Controls.Add(GroupBox5);
            this.TabSheet2.Controls.Add(GroupBox6);
            this.TabSheet2.ResumeLayout(false);
            this.PageControl1.Controls.Add(TabSheet1);
            this.PageControl1.Controls.Add(TabSheet2);
            this.PageControl1.Controls.Add(TabSheet3);
            this.PageControl1.ResumeLayout(false);
            //this.Controls.Add(PageControl1);
            //this.Controls.Add(ButtonSave);
            //this.Controls.Add(ButtonClose);
            //this.ResumeLayout(false);
        }
#endregion

    }
}
