namespace LoginSrv
{
  partial class TFrmUserInfoEdit
    {
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.Label Label11;
        public System.Windows.Forms.Label Label12;
        public System.Windows.Forms.Label Label13;
        public System.Windows.Forms.Label Label14;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.TextBox EdId;
        public System.Windows.Forms.TextBox EdPasswd;
        public System.Windows.Forms.TextBox EdUserName;
        public System.Windows.Forms.TextBox EdBirthDay;
        public System.Windows.Forms.TextBox EdPhone;
        public System.Windows.Forms.Button Button1;
        public System.Windows.Forms.Button Button2;
        public System.Windows.Forms.CheckBox CkFullEdit;
        public System.Windows.Forms.TextBox EdSSNo;
        public System.Windows.Forms.TextBox EdQuiz;
        public System.Windows.Forms.TextBox EdAnswer;
        public System.Windows.Forms.TextBox EdQuiz2;
        public System.Windows.Forms.TextBox EdAnswer2;
        public System.Windows.Forms.TextBox EdMobilePhone;
        public System.Windows.Forms.TextBox EdMemo1;
        public System.Windows.Forms.TextBox EdMemo2;
        public System.Windows.Forms.TextBox EdEMail;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.Label11 = new System.Windows.Forms.Label();
            this.Label12 = new System.Windows.Forms.Label();
            this.Label13 = new System.Windows.Forms.Label();
            this.Label14 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.EdId = new System.Windows.Forms.TextBox();
            this.EdPasswd = new System.Windows.Forms.TextBox();
            this.EdUserName = new System.Windows.Forms.TextBox();
            this.EdBirthDay = new System.Windows.Forms.TextBox();
            this.EdPhone = new System.Windows.Forms.TextBox();
            this.Button1 = new System.Windows.Forms.Button();
            this.Button2 = new System.Windows.Forms.Button();
            this.CkFullEdit = new System.Windows.Forms.CheckBox();
            this.EdSSNo = new System.Windows.Forms.TextBox();
            this.EdQuiz = new System.Windows.Forms.TextBox();
            this.EdAnswer = new System.Windows.Forms.TextBox();
            this.EdQuiz2 = new System.Windows.Forms.TextBox();
            this.EdAnswer2 = new System.Windows.Forms.TextBox();
            this.EdMobilePhone = new System.Windows.Forms.TextBox();
            this.EdMemo1 = new System.Windows.Forms.TextBox();
            this.EdMemo2 = new System.Windows.Forms.TextBox();
            this.EdEMail = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(986, 334);
            this.ClientSize  = new System.Drawing.Size(308, 414);
            this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.AutoScroll = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Name = "FrmUserInfoEdit";
            this.Text = "编辑帐号信息";
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.Label1.Size  = new System.Drawing.Size(30, 12);
            this.Label1.Location  = new System.Drawing.Point(40, 16);
            this.Label1.Text = "帐号:";
            this.Label1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label2.Size  = new System.Drawing.Size(30, 12);
            this.Label2.Location  = new System.Drawing.Point(40, 40);
            this.Label2.Text = "密码:";
            this.Label2.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label3.Size  = new System.Drawing.Size(54, 12);
            this.Label3.Location  = new System.Drawing.Point(16, 64);
            this.Label3.Text = "用户名称:";
            this.Label3.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label4.Size  = new System.Drawing.Size(30, 12);
            this.Label4.Location  = new System.Drawing.Point(40, 112);
            this.Label4.Text = "生日:";
            this.Label4.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label5.Size  = new System.Drawing.Size(30, 12);
            this.Label5.Location  = new System.Drawing.Point(40, 232);
            this.Label5.Text = "电话:";
            this.Label5.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label9.Size  = new System.Drawing.Size(54, 12);
            this.Label9.Location  = new System.Drawing.Point(16, 88);
            this.Label9.Text = "身份证号:";
            this.Label9.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label6.Size  = new System.Drawing.Size(42, 12);
            this.Label6.Location  = new System.Drawing.Point(28, 136);
            this.Label6.Text = "问题一:";
            this.Label6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.Label7.Size  = new System.Drawing.Size(42, 12);
            this.Label7.Location  = new System.Drawing.Point(28, 160);
            this.Label7.Text = "答案一:";
            this.Label7.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label10.Size  = new System.Drawing.Size(42, 12);
            this.Label10.Location  = new System.Drawing.Point(28, 184);
            this.Label10.Text = "问题二:";
            this.Label10.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.Label11.Size  = new System.Drawing.Size(42, 12);
            this.Label11.Location  = new System.Drawing.Point(28, 208);
            this.Label11.Text = "答案二:";
            this.Label11.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label11.Enabled = true;
            this.Label11.Name = "Label11";
            this.Label12.Size  = new System.Drawing.Size(54, 12);
            this.Label12.Location  = new System.Drawing.Point(16, 256);
            this.Label12.Text = "移动电话:";
            this.Label12.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label12.Enabled = true;
            this.Label12.Name = "Label12";
            this.Label13.Size  = new System.Drawing.Size(42, 12);
            this.Label13.Location  = new System.Drawing.Point(28, 280);
            this.Label13.Text = "备注一:";
            this.Label13.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label13.Enabled = true;
            this.Label13.Name = "Label13";
            this.Label14.Size  = new System.Drawing.Size(42, 12);
            this.Label14.Location  = new System.Drawing.Point(28, 304);
            this.Label14.Text = "备注二:";
            this.Label14.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label14.Enabled = true;
            this.Label14.Name = "Label14";
            this.Label8.Size  = new System.Drawing.Size(54, 12);
            this.Label8.Location  = new System.Drawing.Point(16, 328);
            this.Label8.Text = "电子邮箱:";
            this.Label8.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.EdId.Size  = new System.Drawing.Size(121, 20);
            this.EdId.Location  = new System.Drawing.Point(80, 16);
            this.EdId.MaxLength = 30;
            this.EdId.TabIndex = 0;
            this.EdId.Enabled = false;
            this.EdId.Name = "EdId";
            this.EdPasswd.Size  = new System.Drawing.Size(121, 20);
            this.EdPasswd.Location  = new System.Drawing.Point(80, 40);
            this.EdPasswd.MaxLength = 16;
            this.EdPasswd.TabIndex = 1;
            this.EdPasswd.Enabled = true;
            this.EdPasswd.Name = "EdPasswd";
            this.EdUserName.Size  = new System.Drawing.Size(121, 20);
            this.EdUserName.Location  = new System.Drawing.Point(80, 64);
            this.EdUserName.MaxLength = 20;
            this.EdUserName.TabIndex = 2;
            this.EdUserName.Enabled = true;
            this.EdUserName.Name = "EdUserName";
            this.EdBirthDay.Size  = new System.Drawing.Size(121, 20);
            this.EdBirthDay.Location  = new System.Drawing.Point(80, 112);
            this.EdBirthDay.MaxLength = 10;
            this.EdBirthDay.TabIndex = 4;
            this.EdBirthDay.Enabled = true;
            this.EdBirthDay.Name = "EdBirthDay";
            this.EdPhone.Size  = new System.Drawing.Size(121, 20);
            this.EdPhone.Location  = new System.Drawing.Point(80, 232);
            this.EdPhone.MaxLength = 14;
            this.EdPhone.TabIndex = 9;
            this.EdPhone.Enabled = true;
            this.EdPhone.Name = "EdPhone";
            this.Button1.Size  = new System.Drawing.Size(75, 25);
            this.Button1.Location  = new System.Drawing.Point(72, 376);
            this.Button1.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.Button1.TabIndex = 14;
            this.Button1.Name = "Button1";
            this.Button1.Enabled = true;
            this.Button1.Text = "确定(&O)";
            this.Button1.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.Button2.Size  = new System.Drawing.Size(75, 25);
            this.Button2.Location  = new System.Drawing.Point(208, 376);
            this.Button2.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.Button2.TabIndex = 15;
            this.Button2.Name = "Button2";
            this.Button2.Enabled = true;
            this.Button2.Text = "取消(&C)";
            this.Button2.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.CkFullEdit.Size  = new System.Drawing.Size(73, 17);
            this.CkFullEdit.Location  = new System.Drawing.Point(216, 16);
            this.CkFullEdit.Text = "只读";
            this.CkFullEdit.TabIndex = 16;
            this.CkFullEdit.Enabled = true;
            this.CkFullEdit.Click += new System.EventHandler(this.CkFullEditClick);
            this.CkFullEdit.Name = "CkFullEdit";
            this.EdSSNo.Size  = new System.Drawing.Size(121, 20);
            this.EdSSNo.Location  = new System.Drawing.Point(80, 88);
            this.EdSSNo.MaxLength = 14;
            this.EdSSNo.TabIndex = 3;
            this.EdSSNo.Enabled = true;
            this.EdSSNo.Name = "EdSSNo";
            this.EdQuiz.Size  = new System.Drawing.Size(209, 20);
            this.EdQuiz.Location  = new System.Drawing.Point(80, 136);
            this.EdQuiz.MaxLength = 20;
            this.EdQuiz.TabIndex = 5;
            this.EdQuiz.Enabled = true;
            this.EdQuiz.Name = "EdQuiz";
            this.EdAnswer.Size  = new System.Drawing.Size(209, 20);
            this.EdAnswer.Location  = new System.Drawing.Point(80, 160);
            this.EdAnswer.MaxLength = 12;
            this.EdAnswer.TabIndex = 6;
            this.EdAnswer.Enabled = true;
            this.EdAnswer.Name = "EdAnswer";
            this.EdQuiz2.Size  = new System.Drawing.Size(209, 20);
            this.EdQuiz2.Location  = new System.Drawing.Point(80, 184);
            this.EdQuiz2.MaxLength = 20;
            this.EdQuiz2.TabIndex = 7;
            this.EdQuiz2.Enabled = true;
            this.EdQuiz2.Name = "EdQuiz2";
            this.EdAnswer2.Size  = new System.Drawing.Size(209, 20);
            this.EdAnswer2.Location  = new System.Drawing.Point(80, 208);
            this.EdAnswer2.MaxLength = 12;
            this.EdAnswer2.TabIndex = 8;
            this.EdAnswer2.Enabled = true;
            this.EdAnswer2.Name = "EdAnswer2";
            this.EdMobilePhone.Size  = new System.Drawing.Size(121, 20);
            this.EdMobilePhone.Location  = new System.Drawing.Point(80, 256);
            this.EdMobilePhone.MaxLength = 13;
            this.EdMobilePhone.TabIndex = 10;
            this.EdMobilePhone.Enabled = true;
            this.EdMobilePhone.Name = "EdMobilePhone";
            this.EdMemo1.Size  = new System.Drawing.Size(185, 20);
            this.EdMemo1.Location  = new System.Drawing.Point(80, 280);
            this.EdMemo1.MaxLength = 20;
            this.EdMemo1.TabIndex = 11;
            this.EdMemo1.Enabled = true;
            this.EdMemo1.Name = "EdMemo1";
            this.EdMemo2.Size  = new System.Drawing.Size(185, 20);
            this.EdMemo2.Location  = new System.Drawing.Point(80, 304);
            this.EdMemo2.MaxLength = 20;
            this.EdMemo2.TabIndex = 12;
            this.EdMemo2.Enabled = true;
            this.EdMemo2.Name = "EdMemo2";
            this.EdEMail.Size  = new System.Drawing.Size(209, 20);
            this.EdEMail.Location  = new System.Drawing.Point(80, 328);
            this.EdEMail.MaxLength = 40;
            this.EdEMail.TabIndex = 13;
            this.EdEMail.Enabled = true;
            this.EdEMail.Name = "EdEMail";
            this.Controls.Add(Label1);
            this.Controls.Add(Label2);
            this.Controls.Add(Label3);
            this.Controls.Add(Label4);
            this.Controls.Add(Label5);
            this.Controls.Add(Label9);
            this.Controls.Add(Label6);
            this.Controls.Add(Label7);
            this.Controls.Add(Label10);
            this.Controls.Add(Label11);
            this.Controls.Add(Label12);
            this.Controls.Add(Label13);
            this.Controls.Add(Label14);
            this.Controls.Add(Label8);
            this.Controls.Add(EdId);
            this.Controls.Add(EdPasswd);
            this.Controls.Add(EdUserName);
            this.Controls.Add(EdBirthDay);
            this.Controls.Add(EdPhone);
            this.Controls.Add(Button1);
            this.Controls.Add(Button2);
            this.Controls.Add(CkFullEdit);
            this.Controls.Add(EdSSNo);
            this.Controls.Add(EdQuiz);
            this.Controls.Add(EdAnswer);
            this.Controls.Add(EdQuiz2);
            this.Controls.Add(EdAnswer2);
            this.Controls.Add(EdMobilePhone);
            this.Controls.Add(EdMemo1);
            this.Controls.Add(EdMemo2);
            this.Controls.Add(EdEMail);
            this.ResumeLayout(false);
        }
#endregion

    }
}
