namespace LoginSrv
{
  partial class TFrmGateSetting
    {
        public System.Windows.Forms.Button BtnOk;
        public System.Windows.Forms.Button BtnClose;
        public System.Windows.Forms.GroupBox GroupBox1;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.Label Label11;
        public System.Windows.Forms.Label Label12;
        public System.Windows.Forms.Label Label13;
        public System.Windows.Forms.Label Label14;
        public System.Windows.Forms.Label Label15;
        public System.Windows.Forms.Label Label16;
        public System.Windows.Forms.Label Label17;
        public System.Windows.Forms.Label Label18;
        public System.Windows.Forms.CheckBox CkGate1;
        public System.Windows.Forms.TextBox EdGate1;
        public System.Windows.Forms.CheckBox CkGate2;
        public System.Windows.Forms.TextBox EdGate2;
        public System.Windows.Forms.CheckBox CkGate3;
        public System.Windows.Forms.TextBox EdGate3;
        public System.Windows.Forms.CheckBox CkGate4;
        public System.Windows.Forms.TextBox EdGate4;
        public System.Windows.Forms.CheckBox CkGate5;
        public System.Windows.Forms.TextBox EdGate5;
        public System.Windows.Forms.CheckBox CkGate6;
        public System.Windows.Forms.TextBox EdGate6;
        public System.Windows.Forms.CheckBox CkGate7;
        public System.Windows.Forms.TextBox EdGate7;
        public System.Windows.Forms.CheckBox CkGate8;
        public System.Windows.Forms.TextBox EdGate8;
        public System.Windows.Forms.CheckBox CkGate9;
        public System.Windows.Forms.TextBox EdGate9;
        public System.Windows.Forms.CheckBox CkGate10;
        public System.Windows.Forms.TextBox EdGate10;
        public System.Windows.Forms.GroupBox GroupBox2;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.TextBox EdPublicAddr;
        public System.Windows.Forms.TextBox EdPrivateAddr;
        public System.Windows.Forms.GroupBox GroupBox3;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Button BtnChangeTitle;
        public System.Windows.Forms.ComboBox CbGateList;
        public System.Windows.Forms.ComboBox CbServerList;
        public System.Windows.Forms.TextBox EdTitle;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.BtnOk = new System.Windows.Forms.Button();
            this.BtnClose = new System.Windows.Forms.Button();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.Label11 = new System.Windows.Forms.Label();
            this.Label12 = new System.Windows.Forms.Label();
            this.Label13 = new System.Windows.Forms.Label();
            this.Label14 = new System.Windows.Forms.Label();
            this.Label15 = new System.Windows.Forms.Label();
            this.Label16 = new System.Windows.Forms.Label();
            this.Label17 = new System.Windows.Forms.Label();
            this.Label18 = new System.Windows.Forms.Label();
            this.CkGate1 = new System.Windows.Forms.CheckBox();
            this.EdGate1 = new System.Windows.Forms.TextBox();
            this.CkGate2 = new System.Windows.Forms.CheckBox();
            this.EdGate2 = new System.Windows.Forms.TextBox();
            this.CkGate3 = new System.Windows.Forms.CheckBox();
            this.EdGate3 = new System.Windows.Forms.TextBox();
            this.CkGate4 = new System.Windows.Forms.CheckBox();
            this.EdGate4 = new System.Windows.Forms.TextBox();
            this.CkGate5 = new System.Windows.Forms.CheckBox();
            this.EdGate5 = new System.Windows.Forms.TextBox();
            this.CkGate6 = new System.Windows.Forms.CheckBox();
            this.EdGate6 = new System.Windows.Forms.TextBox();
            this.CkGate7 = new System.Windows.Forms.CheckBox();
            this.EdGate7 = new System.Windows.Forms.TextBox();
            this.CkGate8 = new System.Windows.Forms.CheckBox();
            this.EdGate8 = new System.Windows.Forms.TextBox();
            this.CkGate9 = new System.Windows.Forms.CheckBox();
            this.EdGate9 = new System.Windows.Forms.TextBox();
            this.CkGate10 = new System.Windows.Forms.CheckBox();
            this.EdGate10 = new System.Windows.Forms.TextBox();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.EdPublicAddr = new System.Windows.Forms.TextBox();
            this.EdPrivateAddr = new System.Windows.Forms.TextBox();
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label1 = new System.Windows.Forms.Label();
            this.BtnChangeTitle = new System.Windows.Forms.Button();
            this.CbGateList = new System.Windows.Forms.ComboBox();
            this.CbServerList = new System.Windows.Forms.ComboBox();
            this.EdTitle = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(210, 287);
            this.ClientSize  = new System.Drawing.Size(448, 348);
            this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(0)));
            this.Name = "FrmGateSetting";
            this.Text = "网关路由配置";
            this.AutoScroll = true;
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Load += new System.EventHandler(this.FormCreate);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.BtnOk.Size  = new System.Drawing.Size(105, 25);
            this.BtnOk.Location  = new System.Drawing.Point(64, 320);
            this.BtnOk.Click += new System.EventHandler(this.BtnOkClick);
            this.BtnOk.TabIndex = 0;
            this.BtnOk.Name = "BtnOk";
            this.BtnOk.Enabled = true;
            this.BtnOk.Text = "保存(&S)";
            this.BtnOk.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.toolTip1.SetToolTip(this.BtnOk, "将网关路由设置保存到配置文件中。");
            this.BtnClose.Size  = new System.Drawing.Size(75, 25);
            this.BtnClose.Location  = new System.Drawing.Point(336, 320);
            this.BtnClose.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.BtnClose.TabIndex = 1;
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Enabled = true;
            this.BtnClose.Text = "确定(&O)";
            this.BtnClose.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.toolTip1.SetToolTip(this.BtnClose, "退出网关路由配置");
            this.GroupBox1.Size  = new System.Drawing.Size(433, 161);
            this.GroupBox1.Location  = new System.Drawing.Point(8, 152);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.Text = "角色网关设置";
            this.GroupBox1.TabIndex = 2;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.Label5.Size  = new System.Drawing.Size(54, 12);
            this.Label5.Location  = new System.Drawing.Point(32, 16);
            this.Label5.Text = "角色网关:";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label6.Size  = new System.Drawing.Size(48, 12);
            this.Label6.Location  = new System.Drawing.Point(168, 16);
            this.Label6.Text = "是否启用";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.Label7.Size  = new System.Drawing.Size(54, 12);
            this.Label7.Location  = new System.Drawing.Point(240, 16);
            this.Label7.Text = "角色网关:";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label8.Size  = new System.Drawing.Size(48, 12);
            this.Label8.Location  = new System.Drawing.Point(376, 16);
            this.Label8.Text = "是否启用";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.Label9.Size  = new System.Drawing.Size(6, 12);
            this.Label9.Location  = new System.Drawing.Point(15, 36);
            this.Label9.Text = "1";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label10.Size  = new System.Drawing.Size(6, 12);
            this.Label10.Location  = new System.Drawing.Point(15, 60);
            this.Label10.Text = "2";
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.Label11.Size  = new System.Drawing.Size(6, 12);
            this.Label11.Location  = new System.Drawing.Point(15, 84);
            this.Label11.Text = "3";
            this.Label11.Enabled = true;
            this.Label11.Name = "Label11";
            this.Label12.Size  = new System.Drawing.Size(6, 12);
            this.Label12.Location  = new System.Drawing.Point(15, 108);
            this.Label12.Text = "4";
            this.Label12.Enabled = true;
            this.Label12.Name = "Label12";
            this.Label13.Size  = new System.Drawing.Size(6, 12);
            this.Label13.Location  = new System.Drawing.Point(15, 132);
            this.Label13.Text = "5";
            this.Label13.Enabled = true;
            this.Label13.Name = "Label13";
            this.Label14.Size  = new System.Drawing.Size(6, 12);
            this.Label14.Location  = new System.Drawing.Point(223, 36);
            this.Label14.Text = "6";
            this.Label14.Enabled = true;
            this.Label14.Name = "Label14";
            this.Label15.Size  = new System.Drawing.Size(6, 12);
            this.Label15.Location  = new System.Drawing.Point(223, 60);
            this.Label15.Text = "7";
            this.Label15.Enabled = true;
            this.Label15.Name = "Label15";
            this.Label16.Size  = new System.Drawing.Size(6, 12);
            this.Label16.Location  = new System.Drawing.Point(223, 84);
            this.Label16.Text = "8";
            this.Label16.Enabled = true;
            this.Label16.Name = "Label16";
            this.Label17.Size  = new System.Drawing.Size(6, 12);
            this.Label17.Location  = new System.Drawing.Point(223, 108);
            this.Label17.Text = "9";
            this.Label17.Enabled = true;
            this.Label17.Name = "Label17";
            this.Label18.Size  = new System.Drawing.Size(12, 12);
            this.Label18.Location  = new System.Drawing.Point(223, 132);
            this.Label18.Text = "10";
            this.Label18.Enabled = true;
            this.Label18.Name = "Label18";
            this.CkGate1.Size  = new System.Drawing.Size(15, 17);
            this.CkGate1.Location  = new System.Drawing.Point(184, 32);
            this.CkGate1.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate1.TabIndex = 0;
            this.CkGate1.Checked = true;
            this.CkGate1.Name = "CkGate1";
            this.CkGate1.Enabled = true;
            this.CkGate1.Text = "CkGate1";
            this.EdGate1.Size  = new System.Drawing.Size(137, 20);
            this.EdGate1.Location  = new System.Drawing.Point(32, 32);
            this.EdGate1.TabIndex = 1;
            this.EdGate1.Text = "210.121.143.202";
            this.EdGate1.Enabled = true;
            this.EdGate1.Name = "EdGate1";
            this.toolTip1.SetToolTip(this.EdGate1, "角色选择网关IP，及端口。");
            this.CkGate2.Size  = new System.Drawing.Size(15, 17);
            this.CkGate2.Location  = new System.Drawing.Point(184, 56);
            this.CkGate2.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate2.TabIndex = 2;
            this.CkGate2.Checked = true;
            this.CkGate2.Name = "CkGate2";
            this.CkGate2.Enabled = true;
            this.CkGate2.Text = "CheckBox1";
            this.EdGate2.Size  = new System.Drawing.Size(137, 20);
            this.EdGate2.Location  = new System.Drawing.Point(32, 56);
            this.EdGate2.TabIndex = 3;
            this.EdGate2.Text = "210.121.143.203";
            this.EdGate2.Enabled = true;
            this.EdGate2.Name = "EdGate2";
            this.toolTip1.SetToolTip(this.EdGate2, "角色选择网关IP，及端口。");
            this.CkGate3.Size  = new System.Drawing.Size(15, 17);
            this.CkGate3.Location  = new System.Drawing.Point(184, 80);
            this.CkGate3.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate3.TabIndex = 4;
            this.CkGate3.Checked = true;
            this.CkGate3.Name = "CkGate3";
            this.CkGate3.Enabled = true;
            this.CkGate3.Text = "CheckBox1";
            this.EdGate3.Size  = new System.Drawing.Size(137, 20);
            this.EdGate3.Location  = new System.Drawing.Point(32, 80);
            this.EdGate3.TabIndex = 5;
            this.EdGate3.Text = "210.121.143.203";
            this.EdGate3.Enabled = true;
            this.EdGate3.Name = "EdGate3";
            this.toolTip1.SetToolTip(this.EdGate3, "角色选择网关IP，及端口。");
            this.CkGate4.Size  = new System.Drawing.Size(15, 17);
            this.CkGate4.Location  = new System.Drawing.Point(184, 104);
            this.CkGate4.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate4.TabIndex = 6;
            this.CkGate4.Checked = true;
            this.CkGate4.Name = "CkGate4";
            this.CkGate4.Enabled = true;
            this.CkGate4.Text = "CheckBox1";
            this.EdGate4.Size  = new System.Drawing.Size(137, 20);
            this.EdGate4.Location  = new System.Drawing.Point(32, 104);
            this.EdGate4.TabIndex = 7;
            this.EdGate4.Text = "210.121.143.203";
            this.EdGate4.Enabled = true;
            this.EdGate4.Name = "EdGate4";
            this.toolTip1.SetToolTip(this.EdGate4, "角色选择网关IP，及端口。");
            this.CkGate5.Size  = new System.Drawing.Size(15, 17);
            this.CkGate5.Location  = new System.Drawing.Point(184, 128);
            this.CkGate5.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate5.TabIndex = 8;
            this.CkGate5.Checked = true;
            this.CkGate5.Name = "CkGate5";
            this.CkGate5.Enabled = true;
            this.CkGate5.Text = "CheckBox1";
            this.EdGate5.Size  = new System.Drawing.Size(137, 20);
            this.EdGate5.Location  = new System.Drawing.Point(32, 128);
            this.EdGate5.TabIndex = 9;
            this.EdGate5.Text = "210.121.143.203";
            this.EdGate5.Enabled = true;
            this.EdGate5.Name = "EdGate5";
            this.toolTip1.SetToolTip(this.EdGate5, "角色选择网关IP，及端口。");
            this.CkGate6.Size  = new System.Drawing.Size(15, 17);
            this.CkGate6.Location  = new System.Drawing.Point(392, 32);
            this.CkGate6.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate6.TabIndex = 10;
            this.CkGate6.Checked = true;
            this.CkGate6.Name = "CkGate6";
            this.CkGate6.Enabled = true;
            this.CkGate6.Text = "CheckBox1";
            this.EdGate6.Size  = new System.Drawing.Size(137, 20);
            this.EdGate6.Location  = new System.Drawing.Point(240, 32);
            this.EdGate6.TabIndex = 11;
            this.EdGate6.Text = "210.121.143.203";
            this.EdGate6.Enabled = true;
            this.EdGate6.Name = "EdGate6";
            this.toolTip1.SetToolTip(this.EdGate6, "角色选择网关IP，及端口。");
            this.CkGate7.Size  = new System.Drawing.Size(15, 17);
            this.CkGate7.Location  = new System.Drawing.Point(392, 56);
            this.CkGate7.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate7.TabIndex = 12;
            this.CkGate7.Checked = true;
            this.CkGate7.Name = "CkGate7";
            this.CkGate7.Enabled = true;
            this.CkGate7.Text = "CheckBox1";
            this.EdGate7.Size  = new System.Drawing.Size(137, 20);
            this.EdGate7.Location  = new System.Drawing.Point(240, 56);
            this.EdGate7.TabIndex = 13;
            this.EdGate7.Text = "210.121.143.203";
            this.EdGate7.Enabled = true;
            this.EdGate7.Name = "EdGate7";
            this.toolTip1.SetToolTip(this.EdGate7, "角色选择网关IP，及端口。");
            this.CkGate8.Size  = new System.Drawing.Size(15, 17);
            this.CkGate8.Location  = new System.Drawing.Point(392, 80);
            this.CkGate8.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate8.TabIndex = 14;
            this.CkGate8.Checked = true;
            this.CkGate8.Name = "CkGate8";
            this.CkGate8.Enabled = true;
            this.CkGate8.Text = "CheckBox1";
            this.EdGate8.Size  = new System.Drawing.Size(137, 20);
            this.EdGate8.Location  = new System.Drawing.Point(240, 80);
            this.EdGate8.TabIndex = 15;
            this.EdGate8.Text = "210.121.143.203";
            this.EdGate8.Enabled = true;
            this.EdGate8.Name = "EdGate8";
            this.toolTip1.SetToolTip(this.EdGate8, "角色选择网关IP，及端口。");
            this.CkGate9.Size  = new System.Drawing.Size(15, 17);
            this.CkGate9.Location  = new System.Drawing.Point(392, 104);
            this.CkGate9.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate9.TabIndex = 16;
            this.CkGate9.Checked = true;
            this.CkGate9.Name = "CkGate9";
            this.CkGate9.Enabled = true;
            this.CkGate9.Text = "CheckBox1";
            this.EdGate9.Size  = new System.Drawing.Size(137, 20);
            this.EdGate9.Location  = new System.Drawing.Point(240, 104);
            this.EdGate9.TabIndex = 17;
            this.EdGate9.Text = "210.121.143.203";
            this.EdGate9.Enabled = true;
            this.EdGate9.Name = "EdGate9";
            this.toolTip1.SetToolTip(this.EdGate9, "角色选择网关IP，及端口。");
            this.CkGate10.Size  = new System.Drawing.Size(15, 17);
            this.CkGate10.Location  = new System.Drawing.Point(392, 128);
            this.CkGate10.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CkGate10.TabIndex = 18;
            this.CkGate10.Checked = true;
            this.CkGate10.Name = "CkGate10";
            this.CkGate10.Enabled = true;
            this.CkGate10.Text = "CheckBox1";
            this.EdGate10.Size  = new System.Drawing.Size(137, 20);
            this.EdGate10.Location  = new System.Drawing.Point(240, 128);
            this.EdGate10.TabIndex = 19;
            this.EdGate10.Text = "210.121.143.203";
            this.EdGate10.Enabled = true;
            this.EdGate10.Name = "EdGate10";
            this.toolTip1.SetToolTip(this.EdGate10, "角色选择网关IP，及端口。");
            this.GroupBox2.Size  = new System.Drawing.Size(433, 57);
            this.GroupBox2.Location  = new System.Drawing.Point(8, 88);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.Text = "登录网关信息";
            this.GroupBox2.TabIndex = 3;
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label4.Size  = new System.Drawing.Size(54, 12);
            this.Label4.Location  = new System.Drawing.Point(200, 28);
            this.Label4.Text = "外部地址:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label3.Size  = new System.Drawing.Size(54, 12);
            this.Label3.Location  = new System.Drawing.Point(8, 28);
            this.Label3.Text = "内部地址:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.EdPublicAddr.Size  = new System.Drawing.Size(121, 20);
            this.EdPublicAddr.Location  = new System.Drawing.Point(256, 24);
            this.EdPublicAddr.TabIndex = 0;
            this.EdPublicAddr.Text = "210.121.143.202";
            this.EdPublicAddr.Enabled = true;
            this.EdPublicAddr.Name = "EdPublicAddr";
            this.toolTip1.SetToolTip(this.EdPublicAddr, "登录网关对外服务的IP地址。");
            this.EdPrivateAddr.Size  = new System.Drawing.Size(121, 20);
            this.EdPrivateAddr.Location  = new System.Drawing.Point(72, 24);
            this.EdPrivateAddr.TabIndex = 1;
            this.EdPrivateAddr.Text = "5.5.2.1";
            this.EdPrivateAddr.Enabled = true;
            this.EdPrivateAddr.Name = "EdPrivateAddr";
            this.toolTip1.SetToolTip(this.EdPrivateAddr, "登录网关连接到登录服务器IP地址。");
            this.GroupBox3.Size  = new System.Drawing.Size(433, 73);
            this.GroupBox3.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox3.SuspendLayout();
            this.GroupBox3.Text = "网关路由标识";
            this.GroupBox3.TabIndex = 4;
            this.GroupBox3.Enabled = true;
            this.GroupBox3.Name = "GroupBox3";
            this.Label2.Size  = new System.Drawing.Size(54, 12);
            this.Label2.Location  = new System.Drawing.Point(8, 44);
            this.Label2.Text = "路由标识:";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label1.Size  = new System.Drawing.Size(54, 12);
            this.Label1.Location  = new System.Drawing.Point(8, 20);
            this.Label1.Text = "服务器名:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.BtnChangeTitle.Size  = new System.Drawing.Size(57, 22);
            this.BtnChangeTitle.Location  = new System.Drawing.Point(368, 40);
            this.BtnChangeTitle.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.BtnChangeTitle.Text = "修改(&M)";
            this.BtnChangeTitle.Enabled = true;
            this.BtnChangeTitle.Click += new System.EventHandler(this.BtnChangeTitleClick);
            this.BtnChangeTitle.Name = "BtnChangeTitle";
            this.CbGateList.Size  = new System.Drawing.Size(161, 20);
            this.CbGateList.Location  = new System.Drawing.Point(72, 40);
            this.CbGateList.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CbGateList.ItemHeight = 12;
            this.CbGateList.TabIndex = 0;
            this.CbGateList.SelectedIndexChanged += new System.EventHandler(this.CbGateListChange);
            this.CbGateList.Name = "CbGateList";
            this.CbGateList.Enabled = true;
            this.CbServerList.Size  = new System.Drawing.Size(161, 20);
            this.CbServerList.Location  = new System.Drawing.Point(72, 16);
            this.CbServerList.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CbServerList.ItemHeight = 12;
            this.CbServerList.TabIndex = 1;
            this.CbServerList.SelectedIndexChanged += new System.EventHandler(this.CbServerListChange);
            this.CbServerList.Name = "CbServerList";
            this.CbServerList.Enabled = true;
            this.EdTitle.Size  = new System.Drawing.Size(121, 21);
            this.EdTitle.Location  = new System.Drawing.Point(240, 40);
            this.EdTitle.Font  = new System.Drawing.Font("MS Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(1)));
            this.EdTitle.TabIndex = 2;
            this.EdTitle.Enabled = true;
            this.EdTitle.Name = "EdTitle";
            this.GroupBox1.Controls.Add(Label5);
            this.GroupBox1.Controls.Add(Label6);
            this.GroupBox1.Controls.Add(Label7);
            this.GroupBox1.Controls.Add(Label8);
            this.GroupBox1.Controls.Add(Label9);
            this.GroupBox1.Controls.Add(Label10);
            this.GroupBox1.Controls.Add(Label11);
            this.GroupBox1.Controls.Add(Label12);
            this.GroupBox1.Controls.Add(Label13);
            this.GroupBox1.Controls.Add(Label14);
            this.GroupBox1.Controls.Add(Label15);
            this.GroupBox1.Controls.Add(Label16);
            this.GroupBox1.Controls.Add(Label17);
            this.GroupBox1.Controls.Add(Label18);
            this.GroupBox1.Controls.Add(CkGate1);
            this.GroupBox1.Controls.Add(EdGate1);
            this.GroupBox1.Controls.Add(CkGate2);
            this.GroupBox1.Controls.Add(EdGate2);
            this.GroupBox1.Controls.Add(CkGate3);
            this.GroupBox1.Controls.Add(EdGate3);
            this.GroupBox1.Controls.Add(CkGate4);
            this.GroupBox1.Controls.Add(EdGate4);
            this.GroupBox1.Controls.Add(CkGate5);
            this.GroupBox1.Controls.Add(EdGate5);
            this.GroupBox1.Controls.Add(CkGate6);
            this.GroupBox1.Controls.Add(EdGate6);
            this.GroupBox1.Controls.Add(CkGate7);
            this.GroupBox1.Controls.Add(EdGate7);
            this.GroupBox1.Controls.Add(CkGate8);
            this.GroupBox1.Controls.Add(EdGate8);
            this.GroupBox1.Controls.Add(CkGate9);
            this.GroupBox1.Controls.Add(EdGate9);
            this.GroupBox1.Controls.Add(CkGate10);
            this.GroupBox1.Controls.Add(EdGate10);
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox2.Controls.Add(Label4);
            this.GroupBox2.Controls.Add(Label3);
            this.GroupBox2.Controls.Add(EdPublicAddr);
            this.GroupBox2.Controls.Add(EdPrivateAddr);
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox3.Controls.Add(Label2);
            this.GroupBox3.Controls.Add(Label1);
            this.GroupBox3.Controls.Add(BtnChangeTitle);
            this.GroupBox3.Controls.Add(CbGateList);
            this.GroupBox3.Controls.Add(CbServerList);
            this.GroupBox3.Controls.Add(EdTitle);
            this.GroupBox3.ResumeLayout(false);
            this.Controls.Add(BtnOk);
            this.Controls.Add(BtnClose);
            this.Controls.Add(GroupBox1);
            this.Controls.Add(GroupBox2);
            this.Controls.Add(GroupBox3);
            this.ResumeLayout(false);
        }
#endregion

    }
}
