namespace DBServer
{
    partial class TfrmRouteEdit
    {
        public System.Windows.Forms.GroupBox GroupBox1;
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.TextBox EditSelGate;
        public System.Windows.Forms.GroupBox GroupBox2;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.TextBox EditGateIPaddr1;
        public System.Windows.Forms.TextBox EditGateIPaddr2;
        public System.Windows.Forms.TextBox EditGatePort1;
        public System.Windows.Forms.TextBox EditGatePort2;
        public System.Windows.Forms.TextBox EditGateIPaddr3;
        public System.Windows.Forms.TextBox EditGatePort3;
        public System.Windows.Forms.TextBox EditGateIPaddr4;
        public System.Windows.Forms.TextBox EditGatePort4;
        public System.Windows.Forms.TextBox EditGateIPaddr5;
        public System.Windows.Forms.TextBox EditGatePort5;
        public System.Windows.Forms.TextBox EditGateIPaddr6;
        public System.Windows.Forms.TextBox EditGatePort6;
        public System.Windows.Forms.TextBox EditGateIPaddr7;
        public System.Windows.Forms.TextBox EditGatePort7;
        public System.Windows.Forms.TextBox EditGateIPaddr8;
        public System.Windows.Forms.TextBox EditGatePort8;
        public System.Windows.Forms.Button ButtonOK;
        public System.Windows.Forms.Button ButtonCancel;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.EditSelGate = new System.Windows.Forms.TextBox();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.Label9 = new System.Windows.Forms.Label();
            this.EditGateIPaddr1 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr2 = new System.Windows.Forms.TextBox();
            this.EditGatePort1 = new System.Windows.Forms.TextBox();
            this.EditGatePort2 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr3 = new System.Windows.Forms.TextBox();
            this.EditGatePort3 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr4 = new System.Windows.Forms.TextBox();
            this.EditGatePort4 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr5 = new System.Windows.Forms.TextBox();
            this.EditGatePort5 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr6 = new System.Windows.Forms.TextBox();
            this.EditGatePort6 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr7 = new System.Windows.Forms.TextBox();
            this.EditGatePort7 = new System.Windows.Forms.TextBox();
            this.EditGateIPaddr8 = new System.Windows.Forms.TextBox();
            this.EditGatePort8 = new System.Windows.Forms.TextBox();
            this.ButtonOK = new System.Windows.Forms.Button();
            this.ButtonCancel = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.Location = new System.Drawing.Point(653, 337);
            this.ClientSize = new System.Drawing.Size(402, 216);
            this.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AutoScroll = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Name = "frmRouteEdit";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.GroupBox1.Size = new System.Drawing.Size(385, 201);
            this.GroupBox1.Location = new System.Drawing.Point(8, 8);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.TabIndex = 0;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.Label1.Size = new System.Drawing.Size(54, 12);
            this.Label1.Location = new System.Drawing.Point(16, 20);
            this.Label1.Text = "角色网关:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.EditSelGate.Size = new System.Drawing.Size(97, 20);
            this.EditSelGate.Location = new System.Drawing.Point(72, 16);
            this.EditSelGate.TabIndex = 0;
            this.EditSelGate.Enabled = true;
            this.EditSelGate.Name = "EditSelGate";
            this.GroupBox2.Size = new System.Drawing.Size(369, 121);
            this.GroupBox2.Location = new System.Drawing.Point(8, 40);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.TabIndex = 3;
            this.GroupBox2.Text = "游戏网关";
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label2.Size = new System.Drawing.Size(18, 12);
            this.Label2.Location = new System.Drawing.Point(16, 20);
            this.Label2.Text = "一:";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label3.Size = new System.Drawing.Size(18, 12);
            this.Label3.Location = new System.Drawing.Point(16, 44);
            this.Label3.Text = "二:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label4.Size = new System.Drawing.Size(18, 12);
            this.Label4.Location = new System.Drawing.Point(16, 68);
            this.Label4.Text = "三:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label5.Size = new System.Drawing.Size(18, 12);
            this.Label5.Location = new System.Drawing.Point(16, 92);
            this.Label5.Text = "四:";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label6.Size = new System.Drawing.Size(18, 12);
            this.Label6.Location = new System.Drawing.Point(192, 20);
            this.Label6.Text = "五:";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.Label7.Size = new System.Drawing.Size(18, 12);
            this.Label7.Location = new System.Drawing.Point(192, 44);
            this.Label7.Text = "六:";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label8.Size = new System.Drawing.Size(18, 12);
            this.Label8.Location = new System.Drawing.Point(192, 68);
            this.Label8.Text = "七:";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.Label9.Size = new System.Drawing.Size(18, 12);
            this.Label9.Location = new System.Drawing.Point(192, 92);
            this.Label9.Text = "八:";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.EditGateIPaddr1.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr1.Location = new System.Drawing.Point(40, 16);
            this.EditGateIPaddr1.TabIndex = 0;
            this.EditGateIPaddr1.Enabled = true;
            this.EditGateIPaddr1.Name = "EditGateIPaddr1";
            this.EditGateIPaddr2.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr2.Location = new System.Drawing.Point(40, 40);
            this.EditGateIPaddr2.TabIndex = 2;
            this.EditGateIPaddr2.Enabled = true;
            this.EditGateIPaddr2.Name = "EditGateIPaddr2";
            this.EditGatePort1.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort1.Location = new System.Drawing.Point(144, 16);
            this.EditGatePort1.TabIndex = 1;
            this.EditGatePort1.Enabled = true;
            this.EditGatePort1.Name = "EditGatePort1";
            this.EditGatePort2.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort2.Location = new System.Drawing.Point(144, 40);
            this.EditGatePort2.TabIndex = 3;
            this.EditGatePort2.Enabled = true;
            this.EditGatePort2.Name = "EditGatePort2";
            this.EditGateIPaddr3.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr3.Location = new System.Drawing.Point(40, 64);
            this.EditGateIPaddr3.TabIndex = 4;
            this.EditGateIPaddr3.Enabled = true;
            this.EditGateIPaddr3.Name = "EditGateIPaddr3";
            this.EditGatePort3.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort3.Location = new System.Drawing.Point(144, 64);
            this.EditGatePort3.TabIndex = 5;
            this.EditGatePort3.Enabled = true;
            this.EditGatePort3.Name = "EditGatePort3";
            this.EditGateIPaddr4.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr4.Location = new System.Drawing.Point(40, 88);
            this.EditGateIPaddr4.TabIndex = 6;
            this.EditGateIPaddr4.Enabled = true;
            this.EditGateIPaddr4.Name = "EditGateIPaddr4";
            this.EditGatePort4.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort4.Location = new System.Drawing.Point(144, 88);
            this.EditGatePort4.TabIndex = 7;
            this.EditGatePort4.Enabled = true;
            this.EditGatePort4.Name = "EditGatePort4";
            this.EditGateIPaddr5.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr5.Location = new System.Drawing.Point(216, 16);
            this.EditGateIPaddr5.TabIndex = 8;
            this.EditGateIPaddr5.Enabled = true;
            this.EditGateIPaddr5.Name = "EditGateIPaddr5";
            this.EditGatePort5.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort5.Location = new System.Drawing.Point(320, 16);
            this.EditGatePort5.TabIndex = 9;
            this.EditGatePort5.Enabled = true;
            this.EditGatePort5.Name = "EditGatePort5";
            this.EditGateIPaddr6.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr6.Location = new System.Drawing.Point(216, 40);
            this.EditGateIPaddr6.TabIndex = 10;
            this.EditGateIPaddr6.Enabled = true;
            this.EditGateIPaddr6.Name = "EditGateIPaddr6";
            this.EditGatePort6.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort6.Location = new System.Drawing.Point(320, 40);
            this.EditGatePort6.TabIndex = 11;
            this.EditGatePort6.Enabled = true;
            this.EditGatePort6.Name = "EditGatePort6";
            this.EditGateIPaddr7.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr7.Location = new System.Drawing.Point(216, 64);
            this.EditGateIPaddr7.TabIndex = 12;
            this.EditGateIPaddr7.Enabled = true;
            this.EditGateIPaddr7.Name = "EditGateIPaddr7";
            this.EditGatePort7.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort7.Location = new System.Drawing.Point(320, 64);
            this.EditGatePort7.TabIndex = 13;
            this.EditGatePort7.Enabled = true;
            this.EditGatePort7.Name = "EditGatePort7";
            this.EditGateIPaddr8.Size = new System.Drawing.Size(97, 20);
            this.EditGateIPaddr8.Location = new System.Drawing.Point(216, 88);
            this.EditGateIPaddr8.TabIndex = 14;
            this.EditGateIPaddr8.Enabled = true;
            this.EditGateIPaddr8.Name = "EditGateIPaddr8";
            this.EditGatePort8.Size = new System.Drawing.Size(41, 20);
            this.EditGatePort8.Location = new System.Drawing.Point(320, 88);
            this.EditGatePort8.TabIndex = 15;
            this.EditGatePort8.Enabled = true;
            this.EditGatePort8.Name = "EditGatePort8";
            this.ButtonOK.Size = new System.Drawing.Size(73, 25);
            this.ButtonOK.Location = new System.Drawing.Point(8, 168);
            this.ButtonOK.Text = "确定(&O)";
            this.ButtonOK.Click += new System.EventHandler(this.ButtonOKClick);
            this.ButtonOK.TabIndex = 1;
            this.ButtonOK.Name = "ButtonOK";
            this.ButtonOK.Enabled = true;
            this.ButtonOK.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ButtonCancel.Size = new System.Drawing.Size(73, 25);
            this.ButtonCancel.Location = new System.Drawing.Point(88, 168);
            this.ButtonCancel.Text = "取消(&C)";
            this.ButtonCancel.Click += new System.EventHandler(this.ButtonOKClick);
            this.ButtonCancel.TabIndex = 2;
            this.ButtonCancel.Name = "ButtonCancel";
            this.ButtonCancel.Enabled = true;
            this.ButtonCancel.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.GroupBox2.Controls.Add(Label2);
            this.GroupBox2.Controls.Add(Label3);
            this.GroupBox2.Controls.Add(Label4);
            this.GroupBox2.Controls.Add(Label5);
            this.GroupBox2.Controls.Add(Label6);
            this.GroupBox2.Controls.Add(Label7);
            this.GroupBox2.Controls.Add(Label8);
            this.GroupBox2.Controls.Add(Label9);
            this.GroupBox2.Controls.Add(EditGateIPaddr1);
            this.GroupBox2.Controls.Add(EditGateIPaddr2);
            this.GroupBox2.Controls.Add(EditGatePort1);
            this.GroupBox2.Controls.Add(EditGatePort2);
            this.GroupBox2.Controls.Add(EditGateIPaddr3);
            this.GroupBox2.Controls.Add(EditGatePort3);
            this.GroupBox2.Controls.Add(EditGateIPaddr4);
            this.GroupBox2.Controls.Add(EditGatePort4);
            this.GroupBox2.Controls.Add(EditGateIPaddr5);
            this.GroupBox2.Controls.Add(EditGatePort5);
            this.GroupBox2.Controls.Add(EditGateIPaddr6);
            this.GroupBox2.Controls.Add(EditGatePort6);
            this.GroupBox2.Controls.Add(EditGateIPaddr7);
            this.GroupBox2.Controls.Add(EditGatePort7);
            this.GroupBox2.Controls.Add(EditGateIPaddr8);
            this.GroupBox2.Controls.Add(EditGatePort8);
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox1.Controls.Add(Label1);
            this.GroupBox1.Controls.Add(EditSelGate);
            this.GroupBox1.Controls.Add(GroupBox2);
            this.GroupBox1.Controls.Add(ButtonOK);
            this.GroupBox1.Controls.Add(ButtonCancel);
            this.GroupBox1.ResumeLayout(false);
            this.Controls.Add(GroupBox1);
            this.ResumeLayout(false);
        }
        #endregion

    }
}
